package hermes:app;

world hermes {
    include wasi:cli/imports@0.2.6;
    import hermes:cardano/api;
    import hermes:logging/api;
    import hermes:init/api;
    import hermes:sqlite/api;
    
    export hermes:init/event;
    // export hermes:cardano/event-on-block;
}