VERSION 0.8

IMPORT github.com/input-output-hk/catalyst-ci/earthly/wasm/c:v3.5.13 AS wasm-c-ci
# Use when debugging cat-ci locally.
# IMPORT ../../../../catalyst-ci/earthly/wasm/c AS wasm-c-ci

IMPORT ../../../ AS wasm

# build - builds the "cardano_age" example C wasm component
build:
    FROM wasm-c-ci+wasm-c-base

    ARG c_files="cardano_age.c"

    COPY ./$c_files .
    COPY wasm+wasi-src/wasi .

    RUN /scripts/std_build.py --wit_path="wit" --c_files=$c_files --out="cardano_age.c.wasm"

    SAVE ARTIFACT cardano_age.c.wasm
