VERSION 0.8

IMPORT github.com/input-output-hk/catalyst-ci/earthly/wasm/c:v3.5.14 AS wasm-c-ci
# Use when debugging cat-ci locally.
# IMPORT ../../../../catalyst-ci/earthly/wasm/c AS wasm-c-ci

IMPORT ../../../wasi AS wasi

# build - builds the "cardano_age" example C wasm component
build:
    DO wasi+BUILD_C_COMPONENT --c_files="cardano_age.c" --out="cardano_age.c.wasm"
