VERSION 0.8

IMPORT ../../../../ AS hermes
IMPORT ../.. AS athena
    
build-doc-sync:
    DO athena+BUILD_ATHENA_COMPONENT --out=doc_sync.wasm

local-build-doc-sync:
    FROM scratch
    COPY +build-doc-sync/doc_sync.wasm .
    SAVE ARTIFACT doc_sync.wasm AS LOCAL lib/doc_sync.wasm

package-doc-sync-module:
    FROM hermes+build

    COPY lib/ .
    COPY +build-doc-sync/doc_sync.wasm .

    RUN ./target/release/hermes module package manifest_module.json
    SAVE ARTIFACT doc_sync.hmod
