; 3.5.1.  Structs

; cspell: words tstr

Geography = [
    city           : tstr,
    gpsCoordinates : GpsCoordinates,
]

GpsCoordinates = {
    longitude      : uint,            ; degrees, scaled by 10^7
    latitude       : uint,            ; degrees, scaled by 10^7
}

located-samples = {
    "sample-point" => int,
    "samples" => [+ float],
}