; 3.11.  Operator Precedence

t = [group1]
group1 = (a / b // c / d)
a = 1 b = 2 c = 3 d = 4

t = {group2}
group2 = (? ab: a / b // cd: c / d)
a = 1 b = 2 c = 3 d = 4

t = [group3]
group3 = (+ a / b / c)
a = 1 b = 2 c = 3

t = [group4]
group4 = (+ a // b / c)
a = 1 b = 2 c = 3

t = [group4a]
group4a = ((+ a) // (b / c))
a = 1 b = 2 c = 3