; 2.2.2.  Choices

; cspell: words tstr

attire = "bow tie" / "necktie" / "Internet attire"
protocol = 6 / 17

address = { delivery }

delivery = (
street: tstr, ? number: uint, city //
po-box: uint, city //
per-pickup: true )

city = (
name: tstr, zip-code: uint
)