; 3.7.  Unwrapping

basic-header-group = (
    field1: int,
    field2: text,
)

basic-header = [ basic-header-group ]

advanced-header = [
    basic-header-group,
    field3: bytes,
    field4: number, ; as in the tagged type "time"
]

; Unwrapping simplifies this to:

basic-header = [
    field1: int,
    field2: text,
]

advanced-header = [
    ~basic-header,
    field3: bytes,
    field4: ~time,
]