VERSION 0.8

IMPORT github.com/input-output-hk/catalyst-ci/earthly/rust:feat/clarify-hdf5-src-license AS rust-ci
# Use when debugging cat-ci locally.
# IMPORT ../../catalyst-ci/earthly/rust AS rust-ci

IMPORT ../../wasi AS wasi
IMPORT ../../wasi-hermes-component-adapter AS wasi-hermes-component-adapter

# build : build the wasi filesystem integration test wasm component
# This no longer builds. 
# TODO: Fix AFTER wasmtime is bumped to latest version
fails-to-build:
    DO rust-ci+SETUP

    COPY --keep-ts --dir src .
    COPY Cargo.toml .
    COPY wasi+build-rust-bindings/hermes.rs src/hermes.rs

    DO rust-ci+CARGO --args "build --target wasm32-wasip1 --release" \
        --output="wasm32-wasip1/release/wasi_filesystem.wasm"

    COPY wasi-hermes-component-adapter+build/wasi-hermes-component-adapter.wasm wasi_snapshot_preview1.wasm

    RUN wasm-tools component new -o wasi-filesystem.wasm target/wasm32-wasip1/release/wasi_filesystem.wasm --adapt wasi_snapshot_preview1.wasm

    SAVE ARTIFACT wasi-filesystem.wasm

# local-bindings : saves the Hermes rust bindings locally. This is useful for local development.
local-bindings:
    FROM wasi+build-rust-bindings

    SAVE ARTIFACT hermes.rs AS LOCAL src/hermes.rs
