VERSION 0.8

IMPORT github.com/input-output-hk/catalyst-ci/earthly/rust:v3.4.5 AS rust-ci
# Use when debugging cat-ci locally.
# IMPORT ../../catalyst-ci/earthly/rust AS rust-ci

IMPORT ../../wasi AS wasi

# build – build the wasi filesystem integration test wasm component
build:
    DO rust-ci+SETUP

    COPY --keep-ts --dir src .
    COPY Cargo.toml .
    COPY wasi+build-rust-bindings/hermes.rs src/hermes.rs

    DO rust-ci+CARGO --args "build --target wasm32-wasip2 --release" \
        --output="wasi_filesystem.wasm"

    SAVE ARTIFACT target/wasi-filesystem.wasm

# local-bindings : saves the Hermes rust bindings locally. This is useful for local development.
local-bindings:
    FROM wasi+build-rust-bindings

    SAVE ARTIFACT hermes.rs AS LOCAL src/hermes.rs
