VERSION 0.8

IMPORT ../../wasi AS wasi

# build – build the wasi filesystem integration test wasm component
build:
    DO wasi+BUILD_RUST_COMPONENT --wasi-src-dir=../../wasi --out=wasi-filesystem.wasm
