VERSION 0.8

IMPORT ../../../../ AS hermes
IMPORT ../.. AS athena
    
build-rbac-registration:
        DO athena+BUILD_ATHENA_COMPONENT --package=rbac-registration --out=rbac_registration.wasm

local-build-rbac-registration:
    FROM scratch
    COPY +build-rbac-registration/rbac_registration.wasm .
    SAVE ARTIFACT rbac_registration.wasm AS LOCAL lib/rbac_registration.wasm


rbac-registration-package-module:
    FROM hermes+build
    
    COPY lib/ .
    COPY +build-rbac-registration/rbac_registration.wasm .

    RUN ./target/release/hermes module package manifest_module.json
    SAVE ARTIFACT rbac_registration.hmod
