VERSION 0.8

IMPORT github.com/input-output-hk/catalyst-ci/earthly/rust:v3.5.11 AS rust-ci
# Use when debugging cat-ci locally.
# IMPORT ../../../catalyst-ci/earthly/rust AS rust-ci

IMPORT ../../../wasi AS wasi

# build - builds the "cardano_age" example Rust wasm component
build:
    DO wasi+BUILD_RUST_COMPONENT --wasi-src-dir=../../../wasi --rename=cardano_age.rs.wasm
