VERSION 0.7

TINY_GO:
    COMMAND 

    ARG src

    FROM tinygo/tinygo:0.31.2
    WORKDIR /work
    COPY $src .
    COPY ../../wasi+go-binding/bind-gen-go bind-gen-go

   
    RUN tinygo build -o main.wasm -target=wasi ./bind-gen-go/main.go

test:
    FROM golang:1.21-alpine3.19
    WORKDIR /bind-gen-go
    COPY . .
    DO +TINY_GO --src=.
