VERSION 0.7

TINY_GO:
    COMMAND 

    FROM tinygo/tinygo:0.31.2
    ARG src

    COPY $src .
    RUN ls
    RUN tinygo build -o main.wasm -target=wasi ./hermes/hermes.go

test:
    FROM golang:1.21-alpine3.19
    WORKDIR /bind-gen-go
    COPY . .
    COPY ../../wasi+go-binding/bind-gen-go ./hermes

    DO +TINY_GO --src=.
    