VERSION 0.7

#cspell: words fmtchk rustfmt toolsets wasi wasmtime Earthfile

# Set up our target toolchains, and copy source files.
builder:
    DO github.com/input-output-hk/catalyst-ci/earthly/rust:refact/python_scripts+SETUP

    COPY --dir .cargo .config crates .
    COPY Cargo.toml .
    COPY clippy.toml deny.toml rustfmt.toml .

# Run quality checks.
check:
    FROM +builder

    RUN /scripts/std_checks.py

# Build the service.
build:
    FROM +builder

    RUN /scripts/std_build.py   --disable_tests \
                                --disable_benches \
                                --build_flags="--target=wasm32-unknown-unknown"

    SAVE ARTIFACT target/wasm32-unknown-unknown/release/wasi_snapshot_preview1.wasm wasi-component-adapter.wasm
