[package]
name = "voting-index"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = "0.43.0"
serde = { version = "1.0", features = ["derive"] }
tracing = "0.1.41"
regex = "1.10"