VERSION 0.8

IMPORT ../../../../ AS hermes
IMPORT ../.. AS athena
    
build-auth:
    DO athena+BUILD_ATHENA_COMPONENT --out=auth.wasm

local-build-auth:
    FROM scratch
    COPY +build-auth/auth.wasm .
    SAVE ARTIFACT auth.wasm AS LOCAL lib/auth.wasm


auth-package-module:
    FROM hermes+build
    
    COPY lib/ .
    COPY +build-auth/auth.wasm .

    RUN ./target/release/hermes module package manifest_module.json
    SAVE ARTIFACT auth.hmod
