VERSION 0.8

IMPORT ../../../wasm AS wasm
IMPORT github.com/input-output-hk/catalyst-ci/earthly/rust:v3.5.14 AS rust-ci

# Make am Artifact which consists of the shared crate src.
workspace-src:
    FROM scratch

    WORKDIR /
    COPY --keep-ts --dir shared/src ./
    COPY shared/Cargo.toml ./shared/
    COPY Cargo.toml .

    SAVE ARTIFACT .

# Athena modules builder.
builder:
    ARG wasi_src_dir

    DO rust-ci+SETUP

    COPY wasm+wasi-src/wasi $wasi_src_dir
    COPY +workspace-src/* .

# builds a wasm32-wasip2 Athena component and saves it as an artifact
BUILD_ATHENA_COMPONENT:
    FUNCTION

    ARG wasi_src_dir=../../../../../wasm/wasi   # where should the /wasi directory reside at compilation
    ARG --required package
    ARG out=out.wasm                            # name of the saved artifact

    FROM +builder --wasi_src_dir=$wasi_src_dir

    COPY --keep-ts --dir src modules/module/src
    COPY Cargo.toml modules/module/Cargo.toml

    DO rust-ci+CARGO \
        --args "build -p $package --target wasm32-wasip2 --release" \
        --output="wasm32-wasip2/release/$out"

    SAVE ARTIFACT target/wasm32-wasip2/release/$out $out
