VERSION 0.8

IMPORT ../../../wasm AS wasm
IMPORT github.com/input-output-hk/catalyst-ci/earthly/rust:v3.5.17 AS rust-ci

# Make an artifact which consists of the common code shared by Athena modules.
workspace-src:
    FROM scratch

    WORKDIR /
    COPY --keep-ts --dir shared Cargo.toml .

    SAVE ARTIFACT shared
    SAVE ARTIFACT Cargo.toml

# Athena modules builder.
builder:
    ARG wasi_src_dir

    DO rust-ci+SETUP

    COPY wasm+wasi-src/wasi $wasi_src_dir
    COPY --dir +workspace-src/* .

# check-shared : runs native unit tests of the shared crate.
check-shared:
    FROM +builder

    DO rust-ci+CARGO --args="test -p shared"

# check-shared-wasm32 : runs wasm32 unit tests of the shared crate.
check-shared-wasm32:
    FROM +builder

    DO rust-ci+CARGO --args="test -p shared --target=wasm32-wasip2"

# builds a wasm32-wasip2 Athena component and saves it as an artifact
BUILD_ATHENA_COMPONENT:
    FUNCTION

    ARG wasi_src_dir=../../../../../wasm/wasi   # where should the /wasi directory reside at compilation
    ARG out=out.wasm                            # name of the saved artifact

    FROM +builder --wasi_src_dir=$wasi_src_dir

    COPY --keep-ts --dir src Cargo.toml modules/tmp
    WORKDIR modules/tmp

    DO rust-ci+CARGO \
        --args "build --target wasm32-wasip2 --release" \
        --output="wasm32-wasip2/release/$out"

    SAVE ARTIFACT ../../target/wasm32-wasip2/release/$out $out
