VERSION 0.8

IMPORT ../../../wasi AS wasi

# build - builds the "next_century" example Rust wasm component
build:
    DO wasi+BUILD_RUST_COMPONENT --wasi-src-dir=../../../wasi --out=next_century.rs.wasm
