VERSION 0.8

IMPORT ../../../../ AS hermes
IMPORT ../../../../../wasm/wasi AS wasi
IMPORT ../.. AS athena
    
build-rbac-registration-indexer:
        DO athena+BUILD_ATHENA_COMPONENT --out=rbac_registration_indexer.wasm

local-build-rbac-registration-indexer:
    FROM scratch
    COPY +build-rbac-registration-indexer/rbac_registration_indexer.wasm .
    SAVE ARTIFACT rbac_registration_indexer.wasm AS LOCAL lib/rbac_registration_indexer.wasm

rbac-registration-indexer-package-module:
    FROM hermes+build
    
    COPY lib/ .
    COPY +build-rbac-registration_indexer/rbac_registration_indexer.wasm .

    RUN ./target/release/hermes module package manifest_module.json
    SAVE ARTIFACT rbac_registration_indexer.hmod
