VERSION 0.7

# build - Generates a wasm component for the `hash` module to run on unit tests
build:
    FROM github.com/input-output-hk/catalyst-ci/earthly/wasm/c:v2.10.2+wasm-c-base

    COPY . .
    COPY ../..+wasi-src/wasi .

    RUN /scripts/std_build.py --wit_path="wit" --c_files="tests.c" --out="hash-tests.wasm"

    SAVE ARTIFACT hash-tests.wasm

# test - Tests a compiled `hash` component
test:
    FROM ../../../hermes+build

    COPY +build/hash-tests.wasm ../wasm/test-components/

    RUN cargo test --test wasm-component-integration-tests -- --test

test-local:
    FROM ../../../hermes+build

    COPY +build/hash-tests.wasm .

    SAVE ARTIFACT hash-tests.wasm AS LOCAL hash-tests.wasm