VERSION 0.7

# cspell: words wasi autodrop webassembly WORKDIR CFLAGS

build-c-bindings:
    FROM ../wasi-hermes-component-adapter+builder

    RUN wit-bindgen c --autodrop-borrows yes ../wasi/wit

    SAVE ARTIFACT ./

build-c-stub:
    FROM ghcr.io/webassembly/wasi-sdk:wasi-sdk-21
    WORKDIR /repo
    COPY . .
    COPY +build-c-bindings/ ./

    RUN $CC hermes.h hermes_component_type.o my-component.c -o out.wasm $CFLAGS

    SAVE ARTIFACT ./out.wasm

build-c-component:
    FROM ../wasi-hermes-component-adapter+builder

    RUN wasm-tools validate ./out.wasm && \
        wasm-tools component new out.wasm -o component.wasm

    SAVE ARTIFACT ./component.wasm