VERSION 0.7

# cspell: words autodrop CFLAGS mexec

# build-c-bindings generates `wit-bindgen` with C, this should generate `hermes.c`, `hermes.h`, and `hermes_component_type.o`
build-c-bindings:
    FROM ../wasi-hermes-component-adapter+builder

    # FIXME: right now we need to remove `--no-object-file` flag to make it runs with our bench, should we add this back?
    RUN wit-bindgen c --autodrop-borrows yes ../wasi/wit

    SAVE ARTIFACT ./

# build-c-stub compiles the generated C files into .wasm module
build-c-stub:
    FROM ghcr.io/webassembly/wasi-sdk:wasi-sdk-21
    WORKDIR /repo
    COPY . .
    COPY +build-c-bindings/ ./

    RUN $CC hermes.h hermes_component_type.o my-component.c -o out.wasm -mexec-model=reactor $CFLAGS

    SAVE ARTIFACT ./out.wasm

# build-c-component turns a C .wasm module into a component ready to be used with Hermes
build-c-component:
    FROM ../wasi-hermes-component-adapter+builder

    RUN wasm-tools validate ./out.wasm && \
        wasm-tools component new out.wasm -o component.wasm

    SAVE ARTIFACT ./component.wasm