VERSION 0.7

# cspell: words autodrop CFLAGS mexec sysroot

# build - generate a wasm component from a C file
build:
    FROM github.com/input-output-hk/catalyst-ci/earthly/wasm/c:feat/wasm-c-base+wasm-c-base

    COPY ./my-component.c .
    COPY ..+wasi-src/wasi .

    RUN /scripts/std_build.py --wit_path="wit" --c_files="my-component.c" --out="component.wasm"

    SAVE ARTIFACT component.wasm
