[package]
name = "sqlite-test-component"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasmtime = { version = "20.0.2", features = ["component-model"] }
wit-bindgen = "0.24.0"
