VERSION 0.8

IMPORT github.com/input-output-hk/catalyst-ci/earthly/rust:feat/clarify-hdf5-src-license AS rust-ci
# Use when debugging cat-ci locally.
# IMPORT ../../catalyst-ci/earthly/rust AS rust-ci

IMPORT ../../wasi AS wasi
IMPORT ../../wasi-hermes-component-adapter AS wasi-hermes-component-adapter

# gen-bindings - generates `hermes.rs` bindings to work with.
gen-bindings:
    FROM wasi+build-rust-bindings

    SAVE ARTIFACT hermes.rs AS LOCAL src/hermes.rs

# build - builds the sqlite integration test wasm component
build:
    DO rust-ci+SETUP

    COPY --keep-ts --dir src .
    COPY Cargo.toml .
    COPY wasi+build-rust-bindings/hermes.rs src/hermes.rs

    DO rust-ci+CARGO \
        --args "build --target wasm32-wasip1 --release" \
        --output="wasm32-wasip1/release/sqlite_test_component.wasm"

    COPY wasi-hermes-component-adapter+build/wasi-hermes-component-adapter.wasm wasi_snapshot_preview1.wasm

    RUN wasm-tools component new -o sqlite.wasm target/wasm32-wasip1/release/sqlite_test_component.wasm --adapt wasi_snapshot_preview1.wasm

    SAVE ARTIFACT sqlite.wasm
