[package]
name = "http-proxy"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
shared = { path = "../../shared" }
serde = { version = "1.0", features = ["derive"] }
tracing = "0.1.41"
regex = "1.10"