[package]
edition.workspace = true
name = "http-proxy"
version = "0.1.0"

[lints]
workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
shared = { version = "0.1.0", path = "../../shared" }
regex = "1.10"