VERSION 0.8

IMPORT github.com/input-output-hk/catalyst-ci/earthly/wasm/c:v3.5.4 AS wasm-c-ci
# Use when debugging cat-ci locally.
# IMPORT ../../../../catalyst-ci/earthly/wasm/c AS wasm-c-ci

IMPORT ../../../wasi AS wasi

# build - builds the "next_century" example C wasm component
build:
    DO wasi+BUILD_C_COMPONENT --c_files="next_century.c" --out="next_century.c.wasm"
