VERSION 0.8

IMPORT github.com/input-output-hk/catalyst-ci/earthly/rust:v3.2.15 AS rust-ci
# Use when debugging cat-ci locally.
# IMPORT ../../catalyst-ci/earthly/rust AS rust-ci

IMPORT ../../wasi AS wasi
IMPORT ../../wasi-hermes-component-adapter AS wasi-hermes-component-adapter

# gen-bindings - generates `hermes.rs` bindings to work with.
gen-bindings:
    FROM wasi+build-rust-bindings

    SAVE ARTIFACT hermes.rs AS LOCAL src/hermes.rs

# build - builds the IPFS integration test wasm component
build:
    DO rust-ci+SETUP

    COPY --keep-ts --dir src .
    COPY Cargo.toml .
    COPY wasi+build-rust-bindings/hermes.rs src/hermes.rs

    DO rust-ci+CARGO \
        --args "build --target wasm32-unknown-unknown --release" \
        --output="wasm32-unknown-unknown/release/ipfs_test_component.wasm"


    COPY wasi-hermes-component-adapter+build/wasi-hermes-component-adapter.wasm .

    RUN wasm-tools component new -o ipfs.wasm target/wasm32-unknown-unknown/release/ipfs_test_component.wasm --adapt wasi-hermes-component-adapter.wasm
    RUN sha256sum ipfs.wasm

    SAVE ARTIFACT ipfs.wasm
