VERSION 0.7

#cspell: words rustfmt wasi

# Make am Artifact which consists of the WASI SRC.
wasi-src:
    FROM scratch

    WORKDIR /
    COPY --dir wasi .

    SAVE ARTIFACT /wasi wasi

# Build and locally save an output artifact
save-local:
    FROM scratch

    ARG c_files="my-component.c"
    ARG out="c_component.wasm"

    COPY (./event-stubs+build/component.wasm --c_files=$c_files) .
    SAVE ARTIFACT component.wasm AS LOCAL $out
