VERSION 0.7

#cspell: words rustfmt wasi

# Make am Artifact which consists of the WASI SRC.
wasi-src:
    FROM scratch

    WORKDIR /
    COPY --dir wasi .

    SAVE ARTIFACT /wasi wasi

# Build and locally save an output artifact
save-local:
    FROM scratch

    COPY ./event-stubs+build/component.wasm .
    SAVE ARTIFACT component.wasm AS LOCAL c_test_component.wasm