VERSION 0.7

#cspell: words rustfmt wasi

# Make am Artifact which consists of the WASI SRC.
wasi-src:
    FROM scratch

    WORKDIR /
    COPY --dir wasi .

    SAVE ARTIFACT /wasi wasi

# Build and locally save an output artifact
save-c-integration-test-local:
    FROM scratch

    ARG c_files="integration-test.c"
    ARG out="c_test_component.wasm"

    COPY (./c+build/component.wasm --c_files=$c_files) .
    SAVE ARTIFACT component.wasm AS LOCAL test-components/$out

# Build and locally save an crypto test artifact
save-c-crypto-integration-test-local:
    FROM scratch

    ARG c_files="./crypto/test-crypto.c"
    ARG out="c_crypto_test_component.wasm"

    COPY (./integration-tests/c+build/component.wasm --c_files=$c_files) .
    SAVE ARTIFACT component.wasm AS LOCAL test-components/$out