#!/usr/bin/env bash
# One-time P2P initialization for Hermes nodes
#
# This script:
# 1. Starts nodes to generate persistent peer IDs
# 2. Extracts peer IDs from logs
# 3. Creates .env.bootstrap file with custom bootstrap configuration
# 4. Restarts nodes with P2P connectivity enabled
#
# Run once: ./initialize-p2p.sh
# Then use: ./start-nodes.sh normally

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo "🚀 Initializing P2P Bootstrap Configuration"
echo "==========================================="
echo ""

# Check if docker compose is available
if docker compose version &> /dev/null 2>&1; then
    DOCKER_COMPOSE="docker compose"
elif command -v docker-compose &> /dev/null; then
    DOCKER_COMPOSE="docker-compose"
else
    echo "❌ Error: docker compose not found"
    exit 1
fi

# Phase 1: Start nodes to generate peer IDs
echo "📦 Phase 1: Starting nodes to generate peer IDs..."
$DOCKER_COMPOSE up -d

echo "⏳ Waiting for nodes to start up (15 seconds)..."
sleep 15

# Phase 2: Extract peer IDs from logs
echo ""
echo "🔍 Phase 2: Extracting peer IDs from logs..."

# Try to extract peer IDs from logs (rust-ipfs logs the peer ID on startup)
NODE1_ID=$(docker logs hermes-node1 2>&1 | grep -oP 'Local peer id: \K[A-Za-z0-9]+' | head -1 || echo "")
NODE2_ID=$(docker logs hermes-node2 2>&1 | grep -oP 'Local peer id: \K[A-Za-z0-9]+' | head -1 || echo "")
NODE3_ID=$(docker logs hermes-node3 2>&1 | grep -oP 'Local peer id: \K[A-Za-z0-9]+' | head -1 || echo "")

# If grep pattern didn't work, try alternative patterns
if [ -z "$NODE1_ID" ]; then
    NODE1_ID=$(docker logs hermes-node1 2>&1 | grep -oE '12D3KooW[A-Za-z0-9]{44}' | head -1 || echo "")
fi
if [ -z "$NODE2_ID" ]; then
    NODE2_ID=$(docker logs hermes-node2 2>&1 | grep -oE '12D3KooW[A-Za-z0-9]{44}' | head -1 || echo "")
fi
if [ -z "$NODE3_ID" ]; then
    NODE3_ID=$(docker logs hermes-node3 2>&1 | grep -oE '12D3KooW[A-Za-z0-9]{44}' | head -1 || echo "")
fi

# Verify we got all peer IDs
if [ -z "$NODE1_ID" ] || [ -z "$NODE2_ID" ] || [ -z "$NODE3_ID" ]; then
    echo "❌ Failed to extract peer IDs from logs"
    echo ""
    echo "Node 1 ID: ${NODE1_ID:-NOT FOUND}"
    echo "Node 2 ID: ${NODE2_ID:-NOT FOUND}"
    echo "Node 3 ID: ${NODE3_ID:-NOT FOUND}"
    echo ""
    echo "Please check node logs manually:"
    echo "  docker logs hermes-node1 | grep -i peer"
    echo "  docker logs hermes-node2 | grep -i peer"
    echo "  docker logs hermes-node3 | grep -i peer"
    exit 1
fi

echo "✅ Peer IDs extracted:"
echo "   Node 1: $NODE1_ID"
echo "   Node 2: $NODE2_ID"
echo "   Node 3: $NODE3_ID"

# Phase 3: Create .env.bootstrap file
echo ""
echo "📝 Phase 3: Creating bootstrap configuration..."

cat > .env.bootstrap <<EOF
# Bootstrap peer configuration for P2P testing
# Generated by initialize-p2p.sh on $(date)
#
# These environment variables configure each node to bootstrap
# to the other nodes in the Docker network.

# Node 1 bootstraps to Node 2 and Node 3
NODE1_BOOTSTRAP=/ip4/172.20.0.11/tcp/4001/p2p/${NODE2_ID},/ip4/172.20.0.12/tcp/4001/p2p/${NODE3_ID}

# Node 2 bootstraps to Node 1 and Node 3
NODE2_BOOTSTRAP=/ip4/172.20.0.10/tcp/4001/p2p/${NODE1_ID},/ip4/172.20.0.12/tcp/4001/p2p/${NODE3_ID}

# Node 3 bootstraps to Node 1 and Node 2
NODE3_BOOTSTRAP=/ip4/172.20.0.10/tcp/4001/p2p/${NODE1_ID},/ip4/172.20.0.11/tcp/4001/p2p/${NODE2_ID}
EOF

echo "✅ Bootstrap configuration saved to .env.bootstrap"

# Phase 4: Update docker-compose.yml to use bootstrap peers
echo ""
echo "📝 Phase 4: Updating docker-compose.yml..."

# Create a backup
cp docker-compose.yml docker-compose.yml.backup

# Check if IPFS_BOOTSTRAP_PEERS is already in the file
if grep -q "IPFS_BOOTSTRAP_PEERS" docker-compose.yml; then
    echo "⚠️  IPFS_BOOTSTRAP_PEERS already exists in docker-compose.yml"
    echo "   Please manually update or restore from docker-compose.yml.backup"
else
    # Add IPFS_BOOTSTRAP_PEERS to each node's environment
    # This is a simple append - you may need to adjust manually
    echo "ℹ️  Please manually add the following to docker-compose.yml:"
    echo ""
    echo "  hermes-node1:"
    echo "    environment:"
    echo "      - IPFS_BOOTSTRAP_PEERS=/ip4/172.20.0.11/tcp/4001/p2p/${NODE2_ID},/ip4/172.20.0.12/tcp/4001/p2p/${NODE3_ID}"
    echo ""
    echo "  hermes-node2:"
    echo "    environment:"
    echo "      - IPFS_BOOTSTRAP_PEERS=/ip4/172.20.0.10/tcp/4001/p2p/${NODE1_ID},/ip4/172.20.0.12/tcp/4001/p2p/${NODE3_ID}"
    echo ""
    echo "  hermes-node3:"
    echo "    environment:"
    echo "      - IPFS_BOOTSTRAP_PEERS=/ip4/172.20.0.10/tcp/4001/p2p/${NODE1_ID},/ip4/172.20.0.11/tcp/4001/p2p/${NODE2_ID}"
    echo ""
fi

# Phase 5: Instructions
echo ""
echo "✅ Initialization complete!"
echo ""
echo "📋 Next steps:"
echo "1. Update docker-compose.yml with the bootstrap peers (shown above)"
echo "2. Restart nodes: $DOCKER_COMPOSE down && $DOCKER_COMPOSE up -d"
echo "3. Verify connectivity: docker logs hermes-node1 | grep bootstrap"
echo "4. Test PubSub: curl -X POST http://localhost:5000/api/doc-sync/post -H 'Host: athena.hermes.local' -H 'Content-Type: text/plain' -d 'Test message'"
echo ""
echo "💡 The peer IDs are persistent (stored in Docker volumes)."
echo "   You only need to run this script once."
echo ""
