VERSION 0.7
FROM rust:1.69-alpine
WORKDIR /work

build:
    FROM ../../..+tools

    # Get the current modules world definition and WASM interface dependencies.
    COPY --dir ../+wit/wit ./

    # Generate C binding for it (ZIG uses the C binding).
    RUN wit-bindgen c wit

    # TODO - Build a ZIG example
