VERSION 0.7

# Build and locally save an output artifact
save-c-integration-test-local:
    FROM scratch

    ARG c_files="./test/integration-test.c"
    ARG out="c_test_component.wasm"

    COPY (./c+build/component.wasm --c_files=$c_files) .
    SAVE ARTIFACT component.wasm AS LOCAL test-components/$out

save-c-logger-integration-test-local:
    FROM scratch

    ARG c_files="./logger/test-logger.c"
    ARG out="c_logger_test_component.wasm"
    
    COPY (./c+build/component.wasm --c_files=$c_files) .
    SAVE ARTIFACT component.wasm AS LOCAL test-components/$out
