VERSION 0.7
FROM rust:1.69-alpine
WORKDIR /work

build:
    FROM ../../..+tools

    # Get the current modules world definition and WASM interface dependencies.
    COPY --dir ../+wit/wit ./

    # Generate tiny-go binding for it.
    RUN wit-bindgen tiny-go wit

    # TODO - Build a tiny-go example

    RUN --no-cache ls -al
