[package]
name = "byte-array-literals"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[lib]
proc-macro = true
