[package]
name = "byte-array-literals"
license = "Apache-2.0 WITH LLVM-exception"
version.workspace = true
authors.workspace = true
edition.workspace = true
publish = false

[lib]
proc-macro = true
test = false
doctest = false
