VERSION 0.7

# build - generate a wasm component from a C file
build:
    FROM github.com/input-output-hk/catalyst-ci/earthly/wasm/c:v2.9.0+wasm-c-base

    COPY ./my-component.c .
    COPY ..+wasi-src/wasi .

    RUN /scripts/std_build.py --wit_path="wit" --c_files="my-component.c" --out="component.wasm"

    SAVE ARTIFACT component.wasm

# Build and locally save an output artifact
save-local:
    FROM scratch

    COPY +build/component.wasm .
    SAVE ARTIFACT component.wasm AS LOCAL bench_component.wasm
