VERSION 0.7

# build - generate a wasm component from a C stub file
build:
    FROM github.com/input-output-hk/catalyst-ci/earthly/wasm/c:master+wasm-c-base

    ARG c_files="my-component.c"

    COPY ./$c_files .
    COPY ..+wasi-src/wasi .

    RUN /scripts/std_build.py --wit_path="wit" --c_files=$c_files --out="component.wasm"

    SAVE ARTIFACT component.wasm

# Build and locally save an output artifact
save-local:
    FROM scratch

    COPY +build/component.wasm .
    SAVE ARTIFACT component.wasm AS LOCAL bench_component.wasm
