VERSION 0.7
FROM rust:1.69-alpine
WORKDIR /work

build:
    FROM ../../..+tools

    # Get the current modules world definition and WASM interface dependencies.
    COPY --dir ../+wit/wit ./

    COPY --dir Cargo.toml src ./

    RUN --no-cache rustup show

    # Build rust example
    RUN cargo build --target wasm32-wasi
    RUN wasm-tools component new \
        ./target/wasm32-wasi/debug/hermes-logging-example.wasm \
        -o hermes-logging-example-component.wasm \
        --adapt "${WASI+SDK+PATH}/wasi_snapshot_preview1.wasm"

    RUN --no-cache ls -al
