VERSION 0.7

# build - generate a wasm component from a C stub file
build:
    FROM github.com/input-output-hk/catalyst-ci/earthly/wasm/c:v2.11.0+wasm-c-base

    ARG c_files="crypto.c"

    COPY ./$c_files .
    COPY ../..+wasi-src/wasi .

    RUN /scripts/std_build.py --wit_path="wit" --c_files=$c_files --out="crypto.wasm"

    SAVE ARTIFACT crypto.wasm
