# use with https://github.com/casey/just
#
# Hermes developer convenience functions

# cspell: words prereqs, commitlog, rustls, nocapture

default:
    @just --list --unsorted

# Show the dependency tree and all enabled feature flags of every crate.
cargo-tree:
    cargo tree -e features,normal,build -f "{p}[{f}]" --workspace --frozen

# Check Dependency licenses and CVE's
license-check:
    cargo deny check --exclude-dev

# Run long running developer test for mithril downloading.
test-mithril-download:
    RUST_LOG="error,cardano_chain_follower=debug,turbo-downloader=debug,mithril-client=debug,pallas_hardano=error,h2=error,hickory_resolver=error,hickory_proto=error,rustls=error" \
    cargo test follow::tests::test_follow_preprod -- --show-output --ignored --nocapture

# Run long running developer test for mithril downloading.
run-mithril-download-example:
    cargo build -r --package cardano-chain-follower --example follow_chains --features mimalloc
    RUST_LOG="error,follow_chains=debug,cardano_chain_follower=debug,mithril-client=debug" \
    ./target/release/examples/follow_chains --preprod 

# Run long running developer test for mithril downloading.
debug-heap-mithril-download-example:
    cargo build --package cardano-chain-follower --example follow_chains
    RUST_LOG="error,follow_chains=debug,cardano_chain_follower=debug,mithril-client=debug" \
    heaptrack ./target/debug/examples/follow_chains --preprod