// cspell: words rulename VCHAR

// -----------------------------------------------------------------------------
// Test Expressions ONLY TO Be USED by Unit Tests.
// Extends `rfc_5234.pest` with rules needed to properly check sub-rules.

/// Test Expression for the `rule` Rule.
rule_TEST  = ${ SOI ~ rule ~ EOI }

/// Test Expression for the `defined_as` Rule.
defined_as_TEST  = ${ SOI ~ defined_as ~ EOI }

/// Test Expression for the `elements` Rule.
elements_TEST  = ${ SOI ~ elements ~ EOI }

/// Test Expression for the `alternation` Rule.
alternation_TEST  = ${ SOI ~ alternation ~ EOI }

/// Test Expression for the `concatenation` Rule.
concatenation_TEST  = ${ SOI ~ concatenation ~ EOI }

/// Test Expression for the `repetition` Rule.
repetition_TEST  = ${ SOI ~ repetition ~ EOI }

/// Test Expression for the `repeat` Rule.
repeat_TEST  = ${ SOI ~ repeat ~ EOI }

/// Test Expression for the `element` Rule.
element_TEST  = ${ SOI ~ element ~ EOI }

/// Test Expression for the `group` Rule.
group_TEST  = ${ SOI ~ group ~ EOI }

/// Test Expression for the `option` Rule.
option_TEST  = ${ SOI ~ option ~ EOI }

/// Test Expression for the `char_val` Rule.
char_val_TEST  = ${ SOI ~ char_val ~ EOI }

/// Test Expression for the `num_val` Rule.
num_val_TEST  = ${ SOI ~ num_val ~ EOI }

/// Test Expression for the `bin_val` Rule.
bin_val_TEST  = ${ SOI ~ bin_val ~ EOI }

/// Test Expression for the `dec_val` Rule.
dec_val_TEST  = ${ SOI ~ dec_val ~ EOI }

/// Test Expression for the `hex_val` Rule.
hex_val_TEST  = ${ SOI ~ hex_val ~ EOI }

/// Test Expression for the `prose_val` Rule.
prose_val_TEST  = ${ SOI ~ prose_val ~ EOI }

/// Test Expression for the `c_wsp` Rule.
c_wsp_TEST  = ${ SOI ~ c_wsp ~ EOI }

/// Test Expression for the `c_nl` Rule.
c_nl_TEST  = ${ SOI ~ c_nl ~ EOI }

/// Test Expression for the `rulename` Rule.
rulename_TEST  = ${ SOI ~ rulename ~ EOI }

/// Test Expression for the `COMMENT` Rule.
COMMENT_TEST = { SOI ~ COMMENT* ~ EOI }

/// Test Expression for the `WHITESPACE` Rule.
WHITESPACE_TEST = { SOI ~ WHITESPACE* ~ EOI }

/// Test expression to the `VCHAR` Rule.
VCHAR_TEST = ${ SOI ~ VCHAR ~ EOI}
