/// This import every single API and exports every single entrypoint for a module.
/// Modules only need to implement the exports they require.
/// Take not of any permissions attached to a particular API before using it.
default world hermes {

  /// All possible Imports
  import logging: hermes-api.logging
  import database: hermes-api.database

  import monotonic-clock: wasi-clock.monotonic-clock
  import timezone: wasi-clock.timezone
  import wall-clock: wasi-clock.wall-clock
  import cron: hermes-api.cron

  /// All Possible Exports
  export init: hermes-event.init
  export cron-event: hermes-event.cron
}

/// World just for the Hermes `init` Event Handler.
world init {
  export init: hermes-event.init
}

/// World just for the Hermes `logging` API.
world logging {
  import logging: hermes-api.logging
}

/// World just for the Hermes 'cron' API and Event.
world cron {
  import cron: hermes-api.cron
  export cron-event: hermes-event.cron
}

/// World just for the WASI clock API.
world wasi-clock {
  import monotonic-clock: wasi-clock.monotonic-clock
  import timezone: wasi-clock.timezone
  import wall-clock: wasi-clock.wall-clock
}

/// World for the database
world database {
  import database: hermes-api.database
}
