package hermes:app;

/// This exports every single entrypoint for a module.
world hermes {
  /// All possible Hermes exports
  include hermes:binary/all;
  include hermes:cardano/all;
  include hermes:cbor/all;
  include hermes:cron/all;
  include hermes:crypto/all;
  include hermes:hash/all;
  include hermes:init/all;
  include hermes:ipfs/all;
  include hermes:json/all;
  include hermes:kv-store/all;
  include hermes:localtime/all;
  include hermes:logging/all;
  include hermes:sqlite/all;
  include hermes:integration-test/all;
  include hermes:http-gateway/all;
  include hermes:http-request/all;
}
