// Generated by `wit-bindgen` 0.44.0. DO NOT EDIT!
// Options used:
#[allow(dead_code, clippy::all)]
pub mod hermes {
  pub mod binary {
    /// # Binary Data API
    ///
    /// Binary Data types and functions.
    ///
    /// ## Permissions
    ///
    /// This API is ALWAYS available.
    /// cspell: words
    /// Binary API Interface - Imports ONLY
    #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
    pub mod api {
      #[used]
      #[doc(hidden)]
      static __FORCE_SECTION_REF: fn() =
      super::super::super::__link_custom_section_describing_imports;
      
      use super::super::super::_rt;
      /// Binary String (bstr) is a list of bytes.
      ///    This type is used to indicate the data is an arbitrary array of bytes.
      pub type Bstr = _rt::Vec::<u8>;
      /// 256 bit value
      pub type B256 = (u64,u64,u64,u64,);
      /// 512 bit value
      pub type B512 = (u64,u64,u64,u64,u64,u64,u64,u64,);

    }

  }
  pub mod cardano {
    /// # Cardano Blockchain API
    ///
    /// Cardano Blockchain API functionality exposed to the Hermes WASM Modules.
    ///
    /// ## Permissions
    ///
    /// This API is ALWAYS available.
    #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
    pub mod api {
      #[used]
      #[doc(hidden)]
      static __FORCE_SECTION_REF: fn() =
      super::super::super::__link_custom_section_describing_imports;
      
      use super::super::super::_rt;
      pub type Blake2b256 = super::super::super::hermes::hash::api::Blake2b256;
      pub type Cbor = super::super::super::hermes::cbor::api::Cbor;
      /// Slot on the Cardano blockchain.
      pub type Slot = u64;
      /// Cardano transaction index.
      pub type TxnIdx = u16;
      /// Cardano transaction hash.
      pub type TxnHash = Blake2b256;
      /// Cardano blockchain network.
      #[derive(Clone, Copy)]
      pub enum CardanoNetwork {
        /// Cardano Mainnet Network :- "NetworkId": 1, "NetworkMagic": 764824073
        Mainnet,
        /// Cardano Preprod Network :- "NetworkId": 0, "NetworkMagic": 1
        Preprod,
        /// Cardano Preview Network :- "NetworkId": 0, "NetworkMagic": 2
        Preview,
        /// Custom Test Network :- "NetworkId": 0,  "NetworkMagic": u32
        TestnetMagic(u32),
      }
      impl ::core::fmt::Debug for CardanoNetwork {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          match self {
            CardanoNetwork::Mainnet => {
              f.debug_tuple("CardanoNetwork::Mainnet").finish()
            }
            CardanoNetwork::Preprod => {
              f.debug_tuple("CardanoNetwork::Preprod").finish()
            }
            CardanoNetwork::Preview => {
              f.debug_tuple("CardanoNetwork::Preview").finish()
            }
            CardanoNetwork::TestnetMagic(e) => {
              f.debug_tuple("CardanoNetwork::TestnetMagic").field(e).finish()
            }
          }
        }
      }
      /// A sync slot variation.
      #[derive(Clone, Copy)]
      pub enum SyncSlot {
        /// Genesis (first block) of the blockchain.
        Genesis,
        /// A specific slot in the blockchain.
        Specific(Slot),
        /// The live tip of the blockchain, following the upstream node.
        Tip,
        /// The immutable tip of the blockchain
        /// e.g., The last block which has reached the absolute finality and can never rolls back.
        ImmutableTip,
      }
      impl ::core::fmt::Debug for SyncSlot {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          match self {
            SyncSlot::Genesis => {
              f.debug_tuple("SyncSlot::Genesis").finish()
            }
            SyncSlot::Specific(e) => {
              f.debug_tuple("SyncSlot::Specific").field(e).finish()
            }
            SyncSlot::Tip => {
              f.debug_tuple("SyncSlot::Tip").finish()
            }
            SyncSlot::ImmutableTip => {
              f.debug_tuple("SyncSlot::ImmutableTip").finish()
            }
          }
        }
      }
      /// Errors that can happen for subscribing to blocks
      #[repr(u8)]
      #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
      pub enum SubscribeError {
        /// The slot requested is not valid.
        InvalidStartSlot,
      }
      impl SubscribeError{
        pub fn name(&self) -> &'static str {
          match self {
            SubscribeError::InvalidStartSlot => "invalid-start-slot",
          }
        }
        pub fn message(&self) -> &'static str {
          match self {
            SubscribeError::InvalidStartSlot => "The slot requested is not valid.",
          }
        }
      }
      impl ::core::fmt::Debug for SubscribeError{
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          f.debug_struct("SubscribeError")
          .field("code", &(*self as i32))
          .field("name", &self.name())
          .field("message", &self.message())
          .finish()
        }
      }
      impl ::core::fmt::Display for SubscribeError{
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          write!(f, "{} (error {})", self.name(), *self as i32)
        }
      }

      impl std::error::Error for SubscribeError {}

      impl SubscribeError{
        #[doc(hidden)]
        pub unsafe fn _lift(val: u8) -> SubscribeError{
          if !cfg!(debug_assertions) {
            return unsafe { ::core::mem::transmute(val) };
          }

          match val {
            0 => SubscribeError::InvalidStartSlot,

            _ => panic!("invalid enum discriminant"),
          }
        }
      }

      /// Errors that can happen when initialize network.
      #[repr(u8)]
      #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
      pub enum CreateNetworkError {
        /// Network not supported.
        NetworkNotSupported,
      }
      impl CreateNetworkError{
        pub fn name(&self) -> &'static str {
          match self {
            CreateNetworkError::NetworkNotSupported => "network-not-supported",
          }
        }
        pub fn message(&self) -> &'static str {
          match self {
            CreateNetworkError::NetworkNotSupported => "Network not supported.",
          }
        }
      }
      impl ::core::fmt::Debug for CreateNetworkError{
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          f.debug_struct("CreateNetworkError")
          .field("code", &(*self as i32))
          .field("name", &self.name())
          .field("message", &self.message())
          .finish()
        }
      }
      impl ::core::fmt::Display for CreateNetworkError{
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          write!(f, "{} (error {})", self.name(), *self as i32)
        }
      }

      impl std::error::Error for CreateNetworkError {}

      impl CreateNetworkError{
        #[doc(hidden)]
        pub unsafe fn _lift(val: u8) -> CreateNetworkError{
          if !cfg!(debug_assertions) {
            return unsafe { ::core::mem::transmute(val) };
          }

          match val {
            0 => CreateNetworkError::NetworkNotSupported,

            _ => panic!("invalid enum discriminant"),
          }
        }
      }

      /// Errors that can happen for block.
      #[repr(u8)]
      #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
      pub enum BlockError {
        /// Block is not found.
        BlockNotFound,
      }
      impl BlockError{
        pub fn name(&self) -> &'static str {
          match self {
            BlockError::BlockNotFound => "block-not-found",
          }
        }
        pub fn message(&self) -> &'static str {
          match self {
            BlockError::BlockNotFound => "Block is not found.",
          }
        }
      }
      impl ::core::fmt::Debug for BlockError{
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          f.debug_struct("BlockError")
          .field("code", &(*self as i32))
          .field("name", &self.name())
          .field("message", &self.message())
          .finish()
        }
      }
      impl ::core::fmt::Display for BlockError{
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          write!(f, "{} (error {})", self.name(), *self as i32)
        }
      }

      impl std::error::Error for BlockError {}

      impl BlockError{
        #[doc(hidden)]
        pub unsafe fn _lift(val: u8) -> BlockError{
          if !cfg!(debug_assertions) {
            return unsafe { ::core::mem::transmute(val) };
          }

          match val {
            0 => BlockError::BlockNotFound,

            _ => panic!("invalid enum discriminant"),
          }
        }
      }

      /// Errors that can happen for transaction.
      #[repr(u8)]
      #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
      pub enum TransactionError {
        /// Transaction not found
        TxnNotFound,
      }
      impl TransactionError{
        pub fn name(&self) -> &'static str {
          match self {
            TransactionError::TxnNotFound => "txn-not-found",
          }
        }
        pub fn message(&self) -> &'static str {
          match self {
            TransactionError::TxnNotFound => "Transaction not found",
          }
        }
      }
      impl ::core::fmt::Debug for TransactionError{
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          f.debug_struct("TransactionError")
          .field("code", &(*self as i32))
          .field("name", &self.name())
          .field("message", &self.message())
          .finish()
        }
      }
      impl ::core::fmt::Display for TransactionError{
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          write!(f, "{} (error {})", self.name(), *self as i32)
        }
      }

      impl std::error::Error for TransactionError {}

      impl TransactionError{
        #[doc(hidden)]
        pub unsafe fn _lift(val: u8) -> TransactionError{
          if !cfg!(debug_assertions) {
            return unsafe { ::core::mem::transmute(val) };
          }

          match val {
            0 => TransactionError::TxnNotFound,

            _ => panic!("invalid enum discriminant"),
          }
        }
      }

      /// Cardano network

      #[derive(Debug)]
      #[repr(transparent)]
      pub struct Network{
        handle: _rt::Resource<Network>,
      }

      impl Network{
        #[doc(hidden)]
        pub unsafe fn from_handle(handle: u32) -> Self {
          Self {
            handle: unsafe { _rt::Resource::from_handle(handle) },
          }
        }

        #[doc(hidden)]
        pub fn take_handle(&self) -> u32 {
          _rt::Resource::take_handle(&self.handle)
        }

        #[doc(hidden)]
        pub fn handle(&self) -> u32 {
          _rt::Resource::handle(&self.handle)
        }
      }
      

      unsafe impl _rt::WasmResource for Network{
        #[inline]
        unsafe fn drop(_handle: u32) {
          
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "hermes:cardano/api")]
          unsafe extern "C" {
            #[link_name = "[resource-drop]network"]
            fn drop(_: i32, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn drop(_: i32, ) { unreachable!() }
          
          unsafe { drop(_handle as i32); }
        }
      }
      
      /// Cardano block

      #[derive(Debug)]
      #[repr(transparent)]
      pub struct Block{
        handle: _rt::Resource<Block>,
      }

      impl Block{
        #[doc(hidden)]
        pub unsafe fn from_handle(handle: u32) -> Self {
          Self {
            handle: unsafe { _rt::Resource::from_handle(handle) },
          }
        }

        #[doc(hidden)]
        pub fn take_handle(&self) -> u32 {
          _rt::Resource::take_handle(&self.handle)
        }

        #[doc(hidden)]
        pub fn handle(&self) -> u32 {
          _rt::Resource::handle(&self.handle)
        }
      }
      

      unsafe impl _rt::WasmResource for Block{
        #[inline]
        unsafe fn drop(_handle: u32) {
          
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "hermes:cardano/api")]
          unsafe extern "C" {
            #[link_name = "[resource-drop]block"]
            fn drop(_: i32, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn drop(_: i32, ) { unreachable!() }
          
          unsafe { drop(_handle as i32); }
        }
      }
      
      /// Cardano transaction

      #[derive(Debug)]
      #[repr(transparent)]
      pub struct Transaction{
        handle: _rt::Resource<Transaction>,
      }

      impl Transaction{
        #[doc(hidden)]
        pub unsafe fn from_handle(handle: u32) -> Self {
          Self {
            handle: unsafe { _rt::Resource::from_handle(handle) },
          }
        }

        #[doc(hidden)]
        pub fn take_handle(&self) -> u32 {
          _rt::Resource::take_handle(&self.handle)
        }

        #[doc(hidden)]
        pub fn handle(&self) -> u32 {
          _rt::Resource::handle(&self.handle)
        }
      }
      

      unsafe impl _rt::WasmResource for Transaction{
        #[inline]
        unsafe fn drop(_handle: u32) {
          
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "hermes:cardano/api")]
          unsafe extern "C" {
            #[link_name = "[resource-drop]transaction"]
            fn drop(_: i32, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn drop(_: i32, ) { unreachable!() }
          
          unsafe { drop(_handle as i32); }
        }
      }
      

      #[derive(Debug)]
      #[repr(transparent)]
      pub struct SubscriptionId{
        handle: _rt::Resource<SubscriptionId>,
      }

      impl SubscriptionId{
        #[doc(hidden)]
        pub unsafe fn from_handle(handle: u32) -> Self {
          Self {
            handle: unsafe { _rt::Resource::from_handle(handle) },
          }
        }

        #[doc(hidden)]
        pub fn take_handle(&self) -> u32 {
          _rt::Resource::take_handle(&self.handle)
        }

        #[doc(hidden)]
        pub fn handle(&self) -> u32 {
          _rt::Resource::handle(&self.handle)
        }
      }
      

      unsafe impl _rt::WasmResource for SubscriptionId{
        #[inline]
        unsafe fn drop(_handle: u32) {
          
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "hermes:cardano/api")]
          unsafe extern "C" {
            #[link_name = "[resource-drop]subscription-id"]
            fn drop(_: i32, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn drop(_: i32, ) { unreachable!() }
          
          unsafe { drop(_handle as i32); }
        }
      }
      
      impl Network {
        #[allow(unused_unsafe, clippy::all)]
        /// Create a new Cardano network instance.
        ///
        /// **Parameters**
        ///
        /// - `network`: The Cardano network to connect to (e.g., Mainnet, Preprod, Preview).
        ///
        /// **Returns**
        ///
        /// - `ok(network)`: A resource network, if successfully create network resource.
        /// - `error(create-network-error)`: If creating network resource failed.
        #[allow(async_fn_in_trait)]
        pub fn new(network: CardanoNetwork,) -> Result<Network,CreateNetworkError>{
          unsafe {

            #[repr(align(4))]
            struct RetArea([::core::mem::MaybeUninit::<u8>; 8]);
            let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 8]);
            let (result0_0,result0_1,) = match network {
              CardanoNetwork::Mainnet=> {
                (0i32, 0i32)
              }
              CardanoNetwork::Preprod=> {
                (1i32, 0i32)
              }
              CardanoNetwork::Preview=> {
                (2i32, 0i32)
              }
              CardanoNetwork::TestnetMagic(e) => (3i32, _rt::as_i32(e)),
            };
            let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "hermes:cardano/api")]
            unsafe extern "C" {
              #[link_name = "[static]network.new"]
              fn wit_import2(_: i32, _: i32, _: *mut u8, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import2(_: i32, _: i32, _: *mut u8, ) { unreachable!() }
            wit_import2(result0_0, result0_1, ptr1);
            let l3 = i32::from(*ptr1.add(0).cast::<u8>());
            let result6 = match l3 {
              0 => {
                let e = {
                  let l4 = *ptr1.add(4).cast::<i32>();

                  Network::from_handle(l4 as u32)
                };
                Ok(e)
              }
              1 => {
                let e = {
                  let l5 = i32::from(*ptr1.add(4).cast::<u8>());

                  CreateNetworkError::_lift(l5 as u8)
                };
                Err(e)
              }
              _ => _rt::invalid_enum_discriminant(),
            };
            result6
          }
        }
      }
      impl Network {
        #[allow(unused_unsafe, clippy::all)]
        /// Subscribe to blockchain block events, start from a specified starting point.
        ///
        /// This sets up a subscription to receive new block and block rollback updates starting from the
        /// given `start`.
        ///
        /// **Parameters**
        ///
        /// - `start`: The slot to begin following from.
        ///
        /// **Returns**
        ///
        /// - `ok(u32)`: A unsigned integer represent the underlying 32-bit representation of subscription ID
        ///              resource. this subscription. Use to distinguishes events from different subscribers
        ///              and provides control over subscription management.The ID must be unique across all
        ///              active subscriptions.
        /// - `error(subscribe-error)`: If subscription failed.
        #[allow(async_fn_in_trait)]
        pub fn subscribe_block(&self,start: SyncSlot,) -> Result<u32,SubscribeError>{
          unsafe {

            #[repr(align(4))]
            struct RetArea([::core::mem::MaybeUninit::<u8>; 8]);
            let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 8]);
            let (result0_0,result0_1,) = match start {
              SyncSlot::Genesis=> {
                (0i32, 0i64)
              }
              SyncSlot::Specific(e) => (1i32, _rt::as_i64(e)),
              SyncSlot::Tip=> {
                (2i32, 0i64)
              }
              SyncSlot::ImmutableTip=> {
                (3i32, 0i64)
              }
            };
            let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "hermes:cardano/api")]
            unsafe extern "C" {
              #[link_name = "[method]network.subscribe-block"]
              fn wit_import2(_: i32, _: i32, _: i64, _: *mut u8, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import2(_: i32, _: i32, _: i64, _: *mut u8, ) { unreachable!() }
            wit_import2((self).handle() as i32, result0_0, result0_1, ptr1);
            let l3 = i32::from(*ptr1.add(0).cast::<u8>());
            let result6 = match l3 {
              0 => {
                let e = {
                  let l4 = *ptr1.add(4).cast::<i32>();

                  l4 as u32
                };
                Ok(e)
              }
              1 => {
                let e = {
                  let l5 = i32::from(*ptr1.add(4).cast::<u8>());

                  SubscribeError::_lift(l5 as u8)
                };
                Err(e)
              }
              _ => _rt::invalid_enum_discriminant(),
            };
            result6
          }
        }
      }
      impl Network {
        #[allow(unused_unsafe, clippy::all)]
        /// Subscribe to blockchain immutable rolls forward.
        ///
        /// This sets up a subscription to receive event when the immutable part of the blockchain
        /// roll forwards.
        ///
        /// **Parameters**
        ///
        /// - `start`: The slot to begin following from.
        ///
        /// **Returns**
        ///
        /// - `ok(u32)`: A unsigned integer represent the underlying 32-bit representation of subscription ID
        ///              resource. this subscription. Use to distinguishes events from different subscribers
        ///              and provides control over subscription management.The ID must be unique across all
        ///              active subscriptions.
        /// - `error(subscribe-error)`: If subscription failed.
        #[allow(async_fn_in_trait)]
        pub fn subscribe_immutable_roll_forward(&self,start: SyncSlot,) -> Result<u32,SubscribeError>{
          unsafe {

            #[repr(align(4))]
            struct RetArea([::core::mem::MaybeUninit::<u8>; 8]);
            let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 8]);
            let (result0_0,result0_1,) = match start {
              SyncSlot::Genesis=> {
                (0i32, 0i64)
              }
              SyncSlot::Specific(e) => (1i32, _rt::as_i64(e)),
              SyncSlot::Tip=> {
                (2i32, 0i64)
              }
              SyncSlot::ImmutableTip=> {
                (3i32, 0i64)
              }
            };
            let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "hermes:cardano/api")]
            unsafe extern "C" {
              #[link_name = "[method]network.subscribe-immutable-roll-forward"]
              fn wit_import2(_: i32, _: i32, _: i64, _: *mut u8, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import2(_: i32, _: i32, _: i64, _: *mut u8, ) { unreachable!() }
            wit_import2((self).handle() as i32, result0_0, result0_1, ptr1);
            let l3 = i32::from(*ptr1.add(0).cast::<u8>());
            let result6 = match l3 {
              0 => {
                let e = {
                  let l4 = *ptr1.add(4).cast::<i32>();

                  l4 as u32
                };
                Ok(e)
              }
              1 => {
                let e = {
                  let l5 = i32::from(*ptr1.add(4).cast::<u8>());

                  SubscribeError::_lift(l5 as u8)
                };
                Err(e)
              }
              _ => _rt::invalid_enum_discriminant(),
            };
            result6
          }
        }
      }
      impl Network {
        #[allow(unused_unsafe, clippy::all)]
        /// Get a block relative to `start` by `step`.
        ///
        /// **Parameters**
        /// - `start`: Slot to begin retrieval from, current tip if `None`.
        /// - `step`
        ///     -`0` : the block at `start`, will return `None` if there is no block exactly at this `start` slot.
        ///     -`+n`: the `n`‑th block *after* the given `start` slot.
        ///     –`‑n`: the `n`‑th block *before* the given `start` slot.
        ///
        /// Note: For both `+n` and `-n`, the `start` does not need to be a true block.
        /// They will return the block which appears at this block offset, given the arbitrary start point.
        /// IF the `start` block does exist, it will never returned with a positive or negative `step`, as it is `step` 0.
        ///
        /// Example, Given three consecutive blocks at slots `100`, `200` and `300` the following will be returned:
        ///     - `start = 100, step = 0` -> 100 (Exact match)
        ///     - `start = 100, step = 2` -> 300 (Skips 200)
        ///     - `start = 150, step = 1` -> 200 (Rounds up from 150)
        ///     - `start = 200, step = 1` -> 300 (Forward iteration)
        ///     - `start = 300, step = -2` -> 100 (Skips 200)
        ///     - `start = 250, step = -2` -> 100 (Rounds down to 200 first)
        ///
        /// **Returns**
        ///
        /// - Returns a `block` resource, `None` if block cannot be retrieved.
        #[allow(async_fn_in_trait)]
        pub fn get_block(&self,start: Option<Slot>,step: i64,) -> Option<Block>{
          unsafe {

            #[repr(align(4))]
            struct RetArea([::core::mem::MaybeUninit::<u8>; 8]);
            let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 8]);
            let (result0_0,result0_1,) = match start {
              Some(e) => (1i32, _rt::as_i64(e)),
              None => {
                (0i32, 0i64)
              },
            };let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "hermes:cardano/api")]
            unsafe extern "C" {
              #[link_name = "[method]network.get-block"]
              fn wit_import2(_: i32, _: i32, _: i64, _: i64, _: *mut u8, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import2(_: i32, _: i32, _: i64, _: i64, _: *mut u8, ) { unreachable!() }
            wit_import2((self).handle() as i32, result0_0, result0_1, _rt::as_i64(&step), ptr1);
            let l3 = i32::from(*ptr1.add(0).cast::<u8>());
            let result5 = match l3 {
              0 => None,
              1 => {
                let e = {
                  let l4 = *ptr1.add(4).cast::<i32>();

                  Block::from_handle(l4 as u32)
                };
                Some(e)
              }
              _ => _rt::invalid_enum_discriminant(),
            };
            result5
          }
        }
      }
      impl Network {
        #[allow(unused_unsafe, clippy::all)]
        /// Retrieve the current tips of the blockchain.
        ///
        /// **Returns**
        ///
        /// - A tuple of two slots:
        ///   - The immutable tip.
        ///   - The mutable tip.
        /// `None` if the tips cannot be retrieved.
        #[allow(async_fn_in_trait)]
        pub fn get_tips(&self,) -> Option<(Slot,Slot,)>{
          unsafe {

            #[repr(align(8))]
            struct RetArea([::core::mem::MaybeUninit::<u8>; 24]);
            let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 24]);
            let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "hermes:cardano/api")]
            unsafe extern "C" {
              #[link_name = "[method]network.get-tips"]
              fn wit_import1(_: i32, _: *mut u8, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import1(_: i32, _: *mut u8, ) { unreachable!() }
            wit_import1((self).handle() as i32, ptr0);
            let l2 = i32::from(*ptr0.add(0).cast::<u8>());
            let result5 = match l2 {
              0 => None,
              1 => {
                let e = {
                  let l3 = *ptr0.add(8).cast::<i64>();
                  let l4 = *ptr0.add(16).cast::<i64>();

                  (l3 as u64, l4 as u64)
                };
                Some(e)
              }
              _ => _rt::invalid_enum_discriminant(),
            };
            result5
          }
        }
      }
      impl Block {
        #[allow(unused_unsafe, clippy::all)]
        /// Returns whether the block is part of the immutable section of the chain.
        ///
        /// **Returns**
        ///
        /// - `true` if the block is in the immutable part.
        /// - `false` if the block is in the mutable part.
        #[allow(async_fn_in_trait)]
        pub fn is_immutable(&self,) -> bool{
          unsafe {

            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "hermes:cardano/api")]
            unsafe extern "C" {
              #[link_name = "[method]block.is-immutable"]
              fn wit_import0(_: i32, ) -> i32;
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import0(_: i32, ) -> i32 { unreachable!() }
            let ret = wit_import0((self).handle() as i32);
            _rt::bool_lift(ret as u8)
          }
        }
      }
      impl Block {
        #[allow(unused_unsafe, clippy::all)]
        /// Returns whether the block is the first block of a rollback.
        ///
        /// **Returns**
        ///
        /// - `ok(bool)` True if the block is the first block of a rollback,
        ///              otherwise, False.
        /// - `error(block-error)`: If block cannot be retrieved.
        #[allow(async_fn_in_trait)]
        pub fn is_rollback(&self,) -> Result<bool,BlockError>{
          unsafe {

            #[repr(align(1))]
            struct RetArea([::core::mem::MaybeUninit::<u8>; 2]);
            let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 2]);
            let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "hermes:cardano/api")]
            unsafe extern "C" {
              #[link_name = "[method]block.is-rollback"]
              fn wit_import1(_: i32, _: *mut u8, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import1(_: i32, _: *mut u8, ) { unreachable!() }
            wit_import1((self).handle() as i32, ptr0);
            let l2 = i32::from(*ptr0.add(0).cast::<u8>());
            let result5 = match l2 {
              0 => {
                let e = {
                  let l3 = i32::from(*ptr0.add(1).cast::<u8>());

                  _rt::bool_lift(l3 as u8)
                };
                Ok(e)
              }
              1 => {
                let e = {
                  let l4 = i32::from(*ptr0.add(1).cast::<u8>());

                  BlockError::_lift(l4 as u8)
                };
                Err(e)
              }
              _ => _rt::invalid_enum_discriminant(),
            };
            result5
          }
        }
      }
      impl Block {
        #[allow(unused_unsafe, clippy::all)]
        /// Retrieves a transaction at the specified index within the block.
        ///
        /// **Parameters**
        ///
        /// - `index` : The index of the transaction to retrieve.
        ///
        /// **Returns**
        ///
        /// - `ok(transaction)` : A `transaction` resource at the given index
        /// - `error(transaction-error)`: If a transaction data does not exist in the block at the given index.
        #[allow(async_fn_in_trait)]
        pub fn get_txn(&self,index: TxnIdx,) -> Result<Transaction,TransactionError>{
          unsafe {

            #[repr(align(4))]
            struct RetArea([::core::mem::MaybeUninit::<u8>; 8]);
            let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 8]);
            let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "hermes:cardano/api")]
            unsafe extern "C" {
              #[link_name = "[method]block.get-txn"]
              fn wit_import1(_: i32, _: i32, _: *mut u8, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import1(_: i32, _: i32, _: *mut u8, ) { unreachable!() }
            wit_import1((self).handle() as i32, _rt::as_i32(index), ptr0);
            let l2 = i32::from(*ptr0.add(0).cast::<u8>());
            let result5 = match l2 {
              0 => {
                let e = {
                  let l3 = *ptr0.add(4).cast::<i32>();

                  Transaction::from_handle(l3 as u32)
                };
                Ok(e)
              }
              1 => {
                let e = {
                  let l4 = i32::from(*ptr0.add(4).cast::<u8>());

                  TransactionError::_lift(l4 as u8)
                };
                Err(e)
              }
              _ => _rt::invalid_enum_discriminant(),
            };
            result5
          }
        }
      }
      impl Block {
        #[allow(unused_unsafe, clippy::all)]
        /// Retrieves the slot number that this block belongs to.
        ///
        /// **Returns**
        ///
        /// - `slot` : The slot number of the block.
        #[allow(async_fn_in_trait)]
        pub fn get_slot(&self,) -> Slot{
          unsafe {

            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "hermes:cardano/api")]
            unsafe extern "C" {
              #[link_name = "[method]block.get-slot"]
              fn wit_import0(_: i32, ) -> i64;
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import0(_: i32, ) -> i64 { unreachable!() }
            let ret = wit_import0((self).handle() as i32);
            ret as u64
          }
        }
      }
      impl Block {
        #[allow(unused_unsafe, clippy::all)]
        /// Returns the raw CBOR representation of the block.
        ///
        /// **Returns**
        ///
        /// - `cbor` : The CBOR format of the block.
        #[allow(async_fn_in_trait)]
        pub fn raw(&self,) -> Cbor{
          unsafe {

            #[cfg_attr(target_pointer_width="64", repr(align(8)))]
            #[cfg_attr(target_pointer_width="32", repr(align(4)))]
            struct RetArea([::core::mem::MaybeUninit::<u8>; 2*::core::mem::size_of::<*const u8>()]);
            let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 2*::core::mem::size_of::<*const u8>()]);
            let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "hermes:cardano/api")]
            unsafe extern "C" {
              #[link_name = "[method]block.raw"]
              fn wit_import1(_: i32, _: *mut u8, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import1(_: i32, _: *mut u8, ) { unreachable!() }
            wit_import1((self).handle() as i32, ptr0);
            let l2 = *ptr0.add(0).cast::<*mut u8>();
            let l3 = *ptr0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
            let len4 = l3;
            let result5 = _rt::Vec::from_raw_parts(l2.cast(), len4, len4);
            result5
          }
        }
      }
      impl Transaction {
        #[allow(unused_unsafe, clippy::all)]
        /// Returns the transaction auxiliary metadata in CBOR format.
        ///
        /// **Parameters**
        ///
        /// - `label`: A metadata label used as a key to get the associated metadata.
        ///
        /// **Returns**
        ///
        /// - `option<cbor>` : The CBOR format of the metadata, `None` if the label requested is not present.
        #[allow(async_fn_in_trait)]
        pub fn get_metadata(&self,label: u64,) -> Option<Cbor>{
          unsafe {

            #[cfg_attr(target_pointer_width="64", repr(align(8)))]
            #[cfg_attr(target_pointer_width="32", repr(align(4)))]
            struct RetArea([::core::mem::MaybeUninit::<u8>; 3*::core::mem::size_of::<*const u8>()]);
            let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 3*::core::mem::size_of::<*const u8>()]);
            let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "hermes:cardano/api")]
            unsafe extern "C" {
              #[link_name = "[method]transaction.get-metadata"]
              fn wit_import1(_: i32, _: i64, _: *mut u8, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import1(_: i32, _: i64, _: *mut u8, ) { unreachable!() }
            wit_import1((self).handle() as i32, _rt::as_i64(&label), ptr0);
            let l2 = i32::from(*ptr0.add(0).cast::<u8>());
            let result6 = match l2 {
              0 => None,
              1 => {
                let e = {
                  let l3 = *ptr0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                  let l4 = *ptr0.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
                  let len5 = l4;

                  _rt::Vec::from_raw_parts(l3.cast(), len5, len5)
                };
                Some(e)
              }
              _ => _rt::invalid_enum_discriminant(),
            };
            result6
          }
        }
      }
      impl Transaction {
        #[allow(unused_unsafe, clippy::all)]
        /// Returns the transaction hash.
        ///
        /// **Returns**
        ///
        /// - `option<txn-hash>` : Cardano transaction hash - Blake2b-256, `None` if cannot retrieve the transaction hash.
        #[allow(async_fn_in_trait)]
        pub fn get_txn_hash(&self,) -> Option<TxnHash>{
          unsafe {

            #[repr(align(8))]
            struct RetArea([::core::mem::MaybeUninit::<u8>; 40]);
            let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 40]);
            let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "hermes:cardano/api")]
            unsafe extern "C" {
              #[link_name = "[method]transaction.get-txn-hash"]
              fn wit_import1(_: i32, _: *mut u8, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import1(_: i32, _: *mut u8, ) { unreachable!() }
            wit_import1((self).handle() as i32, ptr0);
            let l2 = i32::from(*ptr0.add(0).cast::<u8>());
            let result7 = match l2 {
              0 => None,
              1 => {
                let e = {
                  let l3 = *ptr0.add(8).cast::<i64>();
                  let l4 = *ptr0.add(16).cast::<i64>();
                  let l5 = *ptr0.add(24).cast::<i64>();
                  let l6 = *ptr0.add(32).cast::<i64>();

                  (l3 as u64, l4 as u64, l5 as u64, l6 as u64)
                };
                Some(e)
              }
              _ => _rt::invalid_enum_discriminant(),
            };
            result7
          }
        }
      }
      impl Transaction {
        #[allow(unused_unsafe, clippy::all)]
        /// Returns the raw CBOR representation of the transaction.
        ///
        /// **Returns**
        ///
        /// - `option<cbor>` : The CBOR format of the transaction, `None` if cannot retrieve the raw transaction.
        #[allow(async_fn_in_trait)]
        pub fn raw(&self,) -> Option<Cbor>{
          unsafe {

            #[cfg_attr(target_pointer_width="64", repr(align(8)))]
            #[cfg_attr(target_pointer_width="32", repr(align(4)))]
            struct RetArea([::core::mem::MaybeUninit::<u8>; 3*::core::mem::size_of::<*const u8>()]);
            let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 3*::core::mem::size_of::<*const u8>()]);
            let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "hermes:cardano/api")]
            unsafe extern "C" {
              #[link_name = "[method]transaction.raw"]
              fn wit_import1(_: i32, _: *mut u8, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import1(_: i32, _: *mut u8, ) { unreachable!() }
            wit_import1((self).handle() as i32, ptr0);
            let l2 = i32::from(*ptr0.add(0).cast::<u8>());
            let result6 = match l2 {
              0 => None,
              1 => {
                let e = {
                  let l3 = *ptr0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                  let l4 = *ptr0.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
                  let len5 = l4;

                  _rt::Vec::from_raw_parts(l3.cast(), len5, len5)
                };
                Some(e)
              }
              _ => _rt::invalid_enum_discriminant(),
            };
            result6
          }
        }
      }
      impl SubscriptionId {
        #[allow(unused_unsafe, clippy::all)]
        /// Returns the network that this subscription is in.
        ///
        /// **Returns**
        ///
        /// - `cardano-network` : The Cardano network that this subscription is in.
        #[allow(async_fn_in_trait)]
        pub fn get_network(&self,) -> CardanoNetwork{
          unsafe {

            #[repr(align(4))]
            struct RetArea([::core::mem::MaybeUninit::<u8>; 8]);
            let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 8]);
            let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "hermes:cardano/api")]
            unsafe extern "C" {
              #[link_name = "[method]subscription-id.get-network"]
              fn wit_import1(_: i32, _: *mut u8, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import1(_: i32, _: *mut u8, ) { unreachable!() }
            wit_import1((self).handle() as i32, ptr0);
            let l2 = i32::from(*ptr0.add(0).cast::<u8>());
            let v4 = match l2 {
              0 => {
                CardanoNetwork::Mainnet
              }
              1 => {
                CardanoNetwork::Preprod
              }
              2 => {
                CardanoNetwork::Preview
              }
              n => {
                debug_assert_eq!(n, 3, "invalid enum discriminant");
                let e4 = {
                  let l3 = *ptr0.add(4).cast::<i32>();

                  l3 as u32
                };
                CardanoNetwork::TestnetMagic(e4)
              }
            };
            let result5 = v4;
            result5
          }
        }
      }
      impl SubscriptionId {
        #[allow(unused_unsafe, clippy::all)]
        /// Unsubscribing block event of this `subscription-id` instance.
        /// Once this function is called, the subscription instance, `subscription-id` will be removed.
        #[allow(async_fn_in_trait)]
        pub fn unsubscribe(&self,) -> (){
          unsafe {

            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "hermes:cardano/api")]
            unsafe extern "C" {
              #[link_name = "[method]subscription-id.unsubscribe"]
              fn wit_import0(_: i32, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import0(_: i32, ) { unreachable!() }
            wit_import0((self).handle() as i32);
          }
        }
      }

    }

    /// # Cardano Event API
    ///
    /// Event interfaces that a component must export in order to receive events from the host.
    #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
    pub mod event_on_block {
      #[used]
      #[doc(hidden)]
      static __FORCE_SECTION_REF: fn() =
      super::super::super::__link_custom_section_describing_imports;
      
      pub type Block = super::super::super::hermes::cardano::api::Block;
      pub type SubscriptionId = super::super::super::hermes::cardano::api::SubscriptionId;
      #[allow(unused_unsafe, clippy::all)]
      /// Trigger when a Cardano block event is fired.
      ///
      ///
      /// ## Parameters
      ///
      /// - `subscription-id` : A unique identifier of the block subscription.
      /// - `block` : A block resource where information of the block can be retrieve.
      #[allow(async_fn_in_trait)]
      pub fn on_cardano_block(subscription_id: &SubscriptionId,block: &Block,) -> (){
        unsafe {

          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "hermes:cardano/event-on-block")]
          unsafe extern "C" {
            #[link_name = "on-cardano-block"]
            fn wit_import0(_: i32, _: i32, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import0(_: i32, _: i32, ) { unreachable!() }
          wit_import0((subscription_id).handle() as i32, (block).handle() as i32);
        }
      }

    }


    #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
    pub mod event_on_immutable_roll_forward {
      #[used]
      #[doc(hidden)]
      static __FORCE_SECTION_REF: fn() =
      super::super::super::__link_custom_section_describing_imports;
      
      pub type Block = super::super::super::hermes::cardano::api::Block;
      pub type SubscriptionId = super::super::super::hermes::cardano::api::SubscriptionId;
      #[allow(unused_unsafe, clippy::all)]
      /// Trigger when a Cardano immutable roll-forward event is fired.
      ///
      /// ## Parameters
      ///
      /// - `subscription-id` : A unique identifier of the block subscription.
      /// - `block` : A block resource where information of the block can be retrieve.
      ///
      /// ## Notes
      ///
      /// Roll-forward events are guaranteed to be fully processed **before** the next
      /// block event is delivered. The block event delivered immediately after a
      /// roll-forward will correspond to the block at the roll-forward target `slot`.
      /// This means that roll-forward processing **does not** need to reset or re-subscribe the blockchain follower.
      #[allow(async_fn_in_trait)]
      pub fn on_cardano_immutable_roll_forward(subscription_id: &SubscriptionId,block: &Block,) -> (){
        unsafe {

          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "hermes:cardano/event-on-immutable-roll-forward")]
          unsafe extern "C" {
            #[link_name = "on-cardano-immutable-roll-forward"]
            fn wit_import0(_: i32, _: i32, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import0(_: i32, _: i32, ) { unreachable!() }
          wit_import0((subscription_id).handle() as i32, (block).handle() as i32);
        }
      }

    }

  }
  pub mod cbor {
    /// # CBOR API
    ///
    /// CBOR Data types and functions.
    ///
    /// ## Permissions
    ///
    /// This API is ALWAYS available.
    /// cspell: words
    /// CBOR API Interface - Imports ONLY
    #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
    pub mod api {
      #[used]
      #[doc(hidden)]
      static __FORCE_SECTION_REF: fn() =
      super::super::super::__link_custom_section_describing_imports;
      
      pub type Bstr = super::super::super::hermes::binary::api::Bstr;
      /// CBOR is a binary cbor data type.
      ///    This type is used to indicate the binary array MUST be CBOR data.
      pub type Cbor = Bstr;

    }

  }
  pub mod hash {
    /// # Data Hash API
    ///
    /// Hashing Data types and functions.
    ///
    /// ## Permissions
    ///
    /// This API is ALWAYS available.
    /// Hashing API Interface - Imports ONLY
    #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
    pub mod api {
      #[used]
      #[doc(hidden)]
      static __FORCE_SECTION_REF: fn() =
      super::super::super::__link_custom_section_describing_imports;
      
      use super::super::super::_rt;
      pub type Bstr = super::super::super::hermes::binary::api::Bstr;
      pub type B256 = super::super::super::hermes::binary::api::B256;
      /// A 256-bit (32-byte) cryptographic hash value produced by the BLAKE2b hash function.
      pub type Blake2b256 = B256;
      /// Errors that can occur during hashing.
      #[repr(u8)]
      #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
      pub enum Errno {
        KeyTooBig,
        /// The key exceeds the supported size of the hash function.
        HashTooBig,
        /// The hash size requested is larger than supported by the hash function.
        SaltTooBig,
        /// The salt exceeds the supported size of the hash function.
        PersonalTooBig,
        /// The personal exceeds the supported size of the hash function.
        InvalidDigestByteLength,
      }
      impl Errno{
        pub fn name(&self) -> &'static str {
          match self {
            Errno::KeyTooBig => "key-too-big",
            Errno::HashTooBig => "hash-too-big",
            Errno::SaltTooBig => "salt-too-big",
            Errno::PersonalTooBig => "personal-too-big",
            Errno::InvalidDigestByteLength => "invalid-digest-byte-length",
          }
        }
        pub fn message(&self) -> &'static str {
          match self {
            Errno::KeyTooBig => "",
            Errno::HashTooBig => "The key exceeds the supported size of the hash function.",
            Errno::SaltTooBig => "The hash size requested is larger than supported by the hash function.",
            Errno::PersonalTooBig => "The salt exceeds the supported size of the hash function.",
            Errno::InvalidDigestByteLength => "The personal exceeds the supported size of the hash function.",
          }
        }
      }
      impl ::core::fmt::Debug for Errno{
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          f.debug_struct("Errno")
          .field("code", &(*self as i32))
          .field("name", &self.name())
          .field("message", &self.message())
          .finish()
        }
      }
      impl ::core::fmt::Display for Errno{
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          write!(f, "{} (error {})", self.name(), *self as i32)
        }
      }

      impl std::error::Error for Errno {}

      impl Errno{
        #[doc(hidden)]
        pub unsafe fn _lift(val: u8) -> Errno{
          if !cfg!(debug_assertions) {
            return unsafe { ::core::mem::transmute(val) };
          }

          match val {
            0 => Errno::KeyTooBig,
            1 => Errno::HashTooBig,
            2 => Errno::SaltTooBig,
            3 => Errno::PersonalTooBig,
            4 => Errno::InvalidDigestByteLength,

            _ => panic!("invalid enum discriminant"),
          }
        }
      }

      #[allow(unused_unsafe, clippy::all)]
      /// # BLAKE2s Hash Function
      ///
      /// Hash a binary buffer with BLAKE2s.
      ///
      /// ## Parameters
      ///
      /// - `buf`: The binary data buffer to hash.
      /// - `outlen`: Optional.  The size of the digest.
      ///             If the outlen is not defined, it defaults to 32.
      ///
      /// ## Returns
      ///
      /// - Either a buffer the size requested, with the hash.
      /// - Or an error:
      ///     - `hash_too_big` if `outlen` is specified and is > 32 bytes.
      ///     - `invalid_digest_byte_length` if `outlen` is specified and is = 0.
      #[allow(async_fn_in_trait)]
      pub fn blake2s(buf: &[u8],outlen: Option<u8>,) -> Result<Bstr,Errno>{
        unsafe {

          #[cfg_attr(target_pointer_width="64", repr(align(8)))]
          #[cfg_attr(target_pointer_width="32", repr(align(4)))]
          struct RetArea([::core::mem::MaybeUninit::<u8>; 3*::core::mem::size_of::<*const u8>()]);
          let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 3*::core::mem::size_of::<*const u8>()]);
          let vec0 = buf;
          let ptr0 = vec0.as_ptr().cast::<u8>();
          let len0 = vec0.len();
          let (result1_0,result1_1,) = match outlen {
            Some(e) => (1i32, _rt::as_i32(e)),
            None => {
              (0i32, 0i32)
            },
          };let ptr2 = ret_area.0.as_mut_ptr().cast::<u8>();
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "hermes:hash/api")]
          unsafe extern "C" {
            #[link_name = "blake2s"]
            fn wit_import3(_: *mut u8, _: usize, _: i32, _: i32, _: *mut u8, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import3(_: *mut u8, _: usize, _: i32, _: i32, _: *mut u8, ) { unreachable!() }
          wit_import3(ptr0.cast_mut(), len0, result1_0, result1_1, ptr2);
          let l4 = i32::from(*ptr2.add(0).cast::<u8>());
          let result9 = match l4 {
            0 => {
              let e = {
                let l5 = *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                let l6 = *ptr2.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
                let len7 = l6;

                _rt::Vec::from_raw_parts(l5.cast(), len7, len7)
              };
              Ok(e)
            }
            1 => {
              let e = {
                let l8 = i32::from(*ptr2.add(::core::mem::size_of::<*const u8>()).cast::<u8>());

                Errno::_lift(l8 as u8)
              };
              Err(e)
            }
            _ => _rt::invalid_enum_discriminant(),
          };
          result9
        }
      }
      #[allow(unused_unsafe, clippy::all)]
      /// # BLAKE2sMac Hash Function
      ///
      /// Hash a binary buffer with BLAKE2s with MAC (Message Authentication Code) mode.
      ///
      /// ## Parameters
      ///
      /// - `buf`: The binary data buffer to hash.
      /// - `outlen`: Optional.  The size of the digest.
      ///             If the outlen is not defined, it defaults to 32.
      /// - `key`: The key to use with the hash.
      ///             With MAC mode, key is needed to be defined
      ///             Should not be > 32 bytes.
      /// - `salt`: Optional. Salt uses to increase the randomness and
      ///             uniqueness of the hash output
      ///             Should not be > 8 bytes.
      ///             If not defined, salt is not used.
      /// - `personal`: Optional. Personal allows to
      ///             add customization to the hash function behavior.
      ///             Should not be > 8 bytes.
      ///             If not defined, personal is not used.
      ///
      /// ## Returns
      ///
      /// - Either a buffer the size requested, with the hash.
      /// - Or an error:
      ///     - `key_too_big` if `key` is > 32 bytes.
      ///     - `hash_too_big` if `outlen` is specified and is > 32 bytes.
      ///     - `salt_too_big` if `salt` is specified and is > 8 bytes.
      ///     - `personal_too_big` if `personal` is specified and is > 8 bytes.
      ///
      /// ## Note:
      ///
      /// `key` length is checked before `outlen` so if both sizes are invalid, only
      /// `key_too_big` will be returned.
      /// If `salt` length exceeds 8 bytes, `salt_too_big` will be returned.
      /// if `personal` length exceeds 8 bytes, `personal_too_big` will be returned.
      #[allow(async_fn_in_trait)]
      pub fn blake2smac(buf: &[u8],outlen: Option<u8>,key: &[u8],salt: Option<&[u8]>,personal: Option<&[u8]>,) -> Result<Bstr,Errno>{
        unsafe {

          #[cfg_attr(target_pointer_width="64", repr(align(8)))]
          #[cfg_attr(target_pointer_width="32", repr(align(4)))]
          struct RetArea([::core::mem::MaybeUninit::<u8>; 3*::core::mem::size_of::<*const u8>()]);
          let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 3*::core::mem::size_of::<*const u8>()]);
          let vec0 = buf;
          let ptr0 = vec0.as_ptr().cast::<u8>();
          let len0 = vec0.len();
          let (result1_0,result1_1,) = match outlen {
            Some(e) => (1i32, _rt::as_i32(e)),
            None => {
              (0i32, 0i32)
            },
          };let vec2 = key;
          let ptr2 = vec2.as_ptr().cast::<u8>();
          let len2 = vec2.len();
          let (result4_0,result4_1,result4_2,) = match salt {
            Some(e) => {
              let vec3 = e;
              let ptr3 = vec3.as_ptr().cast::<u8>();
              let len3 = vec3.len();

              (1i32, ptr3.cast_mut(), len3)
            },
            None => {
              (0i32, ::core::ptr::null_mut(), 0usize)
            },
          };let (result6_0,result6_1,result6_2,) = match personal {
            Some(e) => {
              let vec5 = e;
              let ptr5 = vec5.as_ptr().cast::<u8>();
              let len5 = vec5.len();

              (1i32, ptr5.cast_mut(), len5)
            },
            None => {
              (0i32, ::core::ptr::null_mut(), 0usize)
            },
          };let ptr7 = ret_area.0.as_mut_ptr().cast::<u8>();
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "hermes:hash/api")]
          unsafe extern "C" {
            #[link_name = "blake2smac"]
            fn wit_import8(_: *mut u8, _: usize, _: i32, _: i32, _: *mut u8, _: usize, _: i32, _: *mut u8, _: usize, _: i32, _: *mut u8, _: usize, _: *mut u8, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import8(_: *mut u8, _: usize, _: i32, _: i32, _: *mut u8, _: usize, _: i32, _: *mut u8, _: usize, _: i32, _: *mut u8, _: usize, _: *mut u8, ) { unreachable!() }
          wit_import8(ptr0.cast_mut(), len0, result1_0, result1_1, ptr2.cast_mut(), len2, result4_0, result4_1, result4_2, result6_0, result6_1, result6_2, ptr7);
          let l9 = i32::from(*ptr7.add(0).cast::<u8>());
          let result14 = match l9 {
            0 => {
              let e = {
                let l10 = *ptr7.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                let l11 = *ptr7.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
                let len12 = l11;

                _rt::Vec::from_raw_parts(l10.cast(), len12, len12)
              };
              Ok(e)
            }
            1 => {
              let e = {
                let l13 = i32::from(*ptr7.add(::core::mem::size_of::<*const u8>()).cast::<u8>());

                Errno::_lift(l13 as u8)
              };
              Err(e)
            }
            _ => _rt::invalid_enum_discriminant(),
          };
          result14
        }
      }
      #[allow(unused_unsafe, clippy::all)]
      /// # BLAKE2b Hash Function
      ///
      /// Hash a binary buffer with BLAKE2b.
      ///
      /// ## Parameters
      ///
      /// - `buf`: The binary data buffer to hash.
      /// - `outlen`: Optional. The size of the digest.
      ///             If the outlen is not defined, it defaults to 64.
      ///
      /// ## Returns
      ///
      /// - Either a buffer the size requested, with the hash.
      /// - Or an error:
      ///     - `hash_too_big` if `outlen` is specified and is > 64 bytes.
      ///     - `invalid_digest_byte_length` if `outlen` is specified and is = 0.
      #[allow(async_fn_in_trait)]
      pub fn blake2b(buf: &[u8],outlen: Option<u8>,) -> Result<Bstr,Errno>{
        unsafe {

          #[cfg_attr(target_pointer_width="64", repr(align(8)))]
          #[cfg_attr(target_pointer_width="32", repr(align(4)))]
          struct RetArea([::core::mem::MaybeUninit::<u8>; 3*::core::mem::size_of::<*const u8>()]);
          let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 3*::core::mem::size_of::<*const u8>()]);
          let vec0 = buf;
          let ptr0 = vec0.as_ptr().cast::<u8>();
          let len0 = vec0.len();
          let (result1_0,result1_1,) = match outlen {
            Some(e) => (1i32, _rt::as_i32(e)),
            None => {
              (0i32, 0i32)
            },
          };let ptr2 = ret_area.0.as_mut_ptr().cast::<u8>();
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "hermes:hash/api")]
          unsafe extern "C" {
            #[link_name = "blake2b"]
            fn wit_import3(_: *mut u8, _: usize, _: i32, _: i32, _: *mut u8, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import3(_: *mut u8, _: usize, _: i32, _: i32, _: *mut u8, ) { unreachable!() }
          wit_import3(ptr0.cast_mut(), len0, result1_0, result1_1, ptr2);
          let l4 = i32::from(*ptr2.add(0).cast::<u8>());
          let result9 = match l4 {
            0 => {
              let e = {
                let l5 = *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                let l6 = *ptr2.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
                let len7 = l6;

                _rt::Vec::from_raw_parts(l5.cast(), len7, len7)
              };
              Ok(e)
            }
            1 => {
              let e = {
                let l8 = i32::from(*ptr2.add(::core::mem::size_of::<*const u8>()).cast::<u8>());

                Errno::_lift(l8 as u8)
              };
              Err(e)
            }
            _ => _rt::invalid_enum_discriminant(),
          };
          result9
        }
      }
      #[allow(unused_unsafe, clippy::all)]
      /// # BLAKE2bMac Hash Function
      ///
      /// Hash a binary buffer with BLAKE2b with MAC (Message Authentication Code) mode.
      ///
      /// ## Parameters
      ///
      /// - `buf`: The binary data buffer to hash.
      /// - `outlen`: Optional.  The size of the digest.
      ///             If the outlen is not defined, it defaults to 64.
      /// - `key`: The key to use with the hash.
      ///             With MAC mode, key is needed to be defined
      ///             Should not be > 64 bytes.
      /// - `salt`: Optional. Salt uses to increase the randomness and
      ///             uniqueness of the hash output
      ///             Should not be > 16 bytes.
      ///             If not defined, salt is not used.
      /// - `personal`: Optional. Personal allows to
      ///             add customization to the hash function behavior.
      ///             Should not be > 16 bytes.
      ///             If not defined, personal is not used.
      ///
      /// ## Returns
      ///
      /// - Either a buffer the size requested, with the hash.
      /// - Or an error:
      ///     - `key_too_big` if `key` is specified and is > 64 bytes.
      ///     - `hash_too_big` if `outlen` is specified and is > 64 bytes.
      ///     - `salt_too_big` if `salt` is specified and is > 16 bytes.
      ///     - `personal_too_big` if `personal` is specified and is > 16 bytes.
      ///
      /// ## Note:
      ///
      /// `key` length is checked before `outlen` so if both sizes are invalid, only
      /// `key_too_big` will be returned.
      /// If `salt` length exceeds 16 bytes, `salt_too_big` will be returned.
      /// if `personal` length exceeds 16 bytes, `personal_too_big` will be returned.
      #[allow(async_fn_in_trait)]
      pub fn blake2bmac(buf: &[u8],outlen: Option<u8>,key: &[u8],salt: Option<&[u8]>,personal: Option<&[u8]>,) -> Result<Bstr,Errno>{
        unsafe {

          #[cfg_attr(target_pointer_width="64", repr(align(8)))]
          #[cfg_attr(target_pointer_width="32", repr(align(4)))]
          struct RetArea([::core::mem::MaybeUninit::<u8>; 3*::core::mem::size_of::<*const u8>()]);
          let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 3*::core::mem::size_of::<*const u8>()]);
          let vec0 = buf;
          let ptr0 = vec0.as_ptr().cast::<u8>();
          let len0 = vec0.len();
          let (result1_0,result1_1,) = match outlen {
            Some(e) => (1i32, _rt::as_i32(e)),
            None => {
              (0i32, 0i32)
            },
          };let vec2 = key;
          let ptr2 = vec2.as_ptr().cast::<u8>();
          let len2 = vec2.len();
          let (result4_0,result4_1,result4_2,) = match salt {
            Some(e) => {
              let vec3 = e;
              let ptr3 = vec3.as_ptr().cast::<u8>();
              let len3 = vec3.len();

              (1i32, ptr3.cast_mut(), len3)
            },
            None => {
              (0i32, ::core::ptr::null_mut(), 0usize)
            },
          };let (result6_0,result6_1,result6_2,) = match personal {
            Some(e) => {
              let vec5 = e;
              let ptr5 = vec5.as_ptr().cast::<u8>();
              let len5 = vec5.len();

              (1i32, ptr5.cast_mut(), len5)
            },
            None => {
              (0i32, ::core::ptr::null_mut(), 0usize)
            },
          };let ptr7 = ret_area.0.as_mut_ptr().cast::<u8>();
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "hermes:hash/api")]
          unsafe extern "C" {
            #[link_name = "blake2bmac"]
            fn wit_import8(_: *mut u8, _: usize, _: i32, _: i32, _: *mut u8, _: usize, _: i32, _: *mut u8, _: usize, _: i32, _: *mut u8, _: usize, _: *mut u8, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import8(_: *mut u8, _: usize, _: i32, _: i32, _: *mut u8, _: usize, _: i32, _: *mut u8, _: usize, _: i32, _: *mut u8, _: usize, _: *mut u8, ) { unreachable!() }
          wit_import8(ptr0.cast_mut(), len0, result1_0, result1_1, ptr2.cast_mut(), len2, result4_0, result4_1, result4_2, result6_0, result6_1, result6_2, ptr7);
          let l9 = i32::from(*ptr7.add(0).cast::<u8>());
          let result14 = match l9 {
            0 => {
              let e = {
                let l10 = *ptr7.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                let l11 = *ptr7.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
                let len12 = l11;

                _rt::Vec::from_raw_parts(l10.cast(), len12, len12)
              };
              Ok(e)
            }
            1 => {
              let e = {
                let l13 = i32::from(*ptr7.add(::core::mem::size_of::<*const u8>()).cast::<u8>());

                Errno::_lift(l13 as u8)
              };
              Err(e)
            }
            _ => _rt::invalid_enum_discriminant(),
          };
          result14
        }
      }
      #[allow(unused_unsafe, clippy::all)]
      /// # BLAKE3 Hash Function
      ///
      /// Hash a binary buffer with BLAKE3.
      ///
      /// ## Parameters
      ///
      /// - `buf`: The binary data buffer to hash.
      /// - `outlen`: Optional.  The size of the digest.
      ///             If the outlen is not defined, it defaults to 32.
      /// - `key`: Optional. The key to use with the hash.
      ///             If not defined, the hash is not keyed.
      ///             Should not be > 32 bytes.
      ///
      /// ## Returns
      ///
      /// - Either a buffer the size requested, with the hash.
      /// - Or an error:
      ///     - `key_too_big` if `key` is specified and is > 32 bytes.
      ///     - `hash_too_big` if `outlen` is specified and is > 32 bytes.
      ///
      /// ## Note:
      ///
      /// `key` length is checked before `outlen` so if both sizes are invalid, only
      /// `key_too_big` will be returned.
      #[allow(async_fn_in_trait)]
      pub fn blake3(buf: &[u8],outlen: Option<u8>,key: Option<&[u8]>,) -> Result<Bstr,Errno>{
        unsafe {

          #[cfg_attr(target_pointer_width="64", repr(align(8)))]
          #[cfg_attr(target_pointer_width="32", repr(align(4)))]
          struct RetArea([::core::mem::MaybeUninit::<u8>; 3*::core::mem::size_of::<*const u8>()]);
          let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 3*::core::mem::size_of::<*const u8>()]);
          let vec0 = buf;
          let ptr0 = vec0.as_ptr().cast::<u8>();
          let len0 = vec0.len();
          let (result1_0,result1_1,) = match outlen {
            Some(e) => (1i32, _rt::as_i32(e)),
            None => {
              (0i32, 0i32)
            },
          };let (result3_0,result3_1,result3_2,) = match key {
            Some(e) => {
              let vec2 = e;
              let ptr2 = vec2.as_ptr().cast::<u8>();
              let len2 = vec2.len();

              (1i32, ptr2.cast_mut(), len2)
            },
            None => {
              (0i32, ::core::ptr::null_mut(), 0usize)
            },
          };let ptr4 = ret_area.0.as_mut_ptr().cast::<u8>();
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "hermes:hash/api")]
          unsafe extern "C" {
            #[link_name = "blake3"]
            fn wit_import5(_: *mut u8, _: usize, _: i32, _: i32, _: i32, _: *mut u8, _: usize, _: *mut u8, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import5(_: *mut u8, _: usize, _: i32, _: i32, _: i32, _: *mut u8, _: usize, _: *mut u8, ) { unreachable!() }
          wit_import5(ptr0.cast_mut(), len0, result1_0, result1_1, result3_0, result3_1, result3_2, ptr4);
          let l6 = i32::from(*ptr4.add(0).cast::<u8>());
          let result11 = match l6 {
            0 => {
              let e = {
                let l7 = *ptr4.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                let l8 = *ptr4.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
                let len9 = l8;

                _rt::Vec::from_raw_parts(l7.cast(), len9, len9)
              };
              Ok(e)
            }
            1 => {
              let e = {
                let l10 = i32::from(*ptr4.add(::core::mem::size_of::<*const u8>()).cast::<u8>());

                Errno::_lift(l10 as u8)
              };
              Err(e)
            }
            _ => _rt::invalid_enum_discriminant(),
          };
          result11
        }
      }

    }

  }
  pub mod init {
    /// # Init API
    ///
    /// The Init Event is only ever called once per application the webasm module is used in.
    ///
    /// ## Permissions
    ///
    /// This API is ALWAYS available.
    /// Logging API Interface
    #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
    pub mod event {
      #[used]
      #[doc(hidden)]
      static __FORCE_SECTION_REF: fn() =
      super::super::super::__link_custom_section_describing_imports;
      
      use super::super::super::_rt;
      #[allow(unused_unsafe, clippy::all)]
      /// Perform application start up initialization.
      ///
      /// This will only ever be called once when the application this module is a part of is started.
      /// The module must export this interface to use it.
      ///
      /// Returns:
      /// - `true`  - Initialization is successful, the application may commence.
      /// - `false` - Fatal error during Initialization.  DO NOT START APPLICATION.
      #[allow(async_fn_in_trait)]
      pub fn init() -> bool{
        unsafe {

          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "hermes:init/event")]
          unsafe extern "C" {
            #[link_name = "init"]
            fn wit_import0() -> i32;
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import0() -> i32 { unreachable!() }
          let ret = wit_import0();
          _rt::bool_lift(ret as u8)
        }
      }

    }

  }
}
#[allow(dead_code, clippy::all)]
pub mod exports {

  #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
  pub mod event {
    #[used]
    #[doc(hidden)]
    static __FORCE_SECTION_REF: fn() =
    super::super::__link_custom_section_describing_imports;
    
    use super::super::_rt;
    pub type Block = super::super::hermes::cardano::api::Block;
    pub type SubscriptionId = super::super::hermes::cardano::api::SubscriptionId;
    #[doc(hidden)]
    #[allow(non_snake_case, unused_unsafe)]
    pub unsafe fn _export_init_cabi<T: Guest>() -> i32 { unsafe {#[cfg(target_arch="wasm32")]
    _rt::run_ctors_once();let result0 = {
      T::init()
    };
    match result0 { true => 1, false => 0 }
  } }
  #[doc(hidden)]
  #[allow(non_snake_case, unused_unsafe)]
  pub unsafe fn _export_on_cardano_block_cabi<T: Guest>(arg0: i32,arg1: i32,) { unsafe {#[cfg(target_arch="wasm32")]
  _rt::run_ctors_once();{
    let handle0;let handle1;T::on_cardano_block({

      handle0 = super::super::hermes::cardano::api::SubscriptionId::from_handle(arg0 as u32);
      &handle0
    }, {

      handle1 = super::super::hermes::cardano::api::Block::from_handle(arg1 as u32);
      &handle1
    })
  };
} }
#[doc(hidden)]
#[allow(non_snake_case, unused_unsafe)]
pub unsafe fn _export_on_cardano_immutable_roll_forward_cabi<T: Guest>(arg0: i32,arg1: i32,) { unsafe {#[cfg(target_arch="wasm32")]
_rt::run_ctors_once();{
  let handle0;let handle1;T::on_cardano_immutable_roll_forward({

    handle0 = super::super::hermes::cardano::api::SubscriptionId::from_handle(arg0 as u32);
    &handle0
  }, {

    handle1 = super::super::hermes::cardano::api::Block::from_handle(arg1 as u32);
    &handle1
  })
};
} }
pub trait Guest {
  #[allow(async_fn_in_trait)]
  fn init() -> bool;
  #[allow(async_fn_in_trait)]
  fn on_cardano_block(subscription_id: &SubscriptionId,block: &Block,) -> ();
  #[allow(async_fn_in_trait)]
  fn on_cardano_immutable_roll_forward(subscription_id: &SubscriptionId,block: &Block,) -> ();
}
#[doc(hidden)]

macro_rules! __export_event_cabi{
  ($ty:ident with_types_in $($path_to_types:tt)*) => (const _: () = {

    #[unsafe(export_name = "event#init")]
    unsafe extern "C" fn export_init() -> i32 {
      unsafe { $($path_to_types)*::_export_init_cabi::<$ty>() }
    }
    #[unsafe(export_name = "event#on-cardano-block")]
    unsafe extern "C" fn export_on_cardano_block(arg0: i32,arg1: i32,) {
      unsafe { $($path_to_types)*::_export_on_cardano_block_cabi::<$ty>(arg0, arg1) }
    }
    #[unsafe(export_name = "event#on-cardano-immutable-roll-forward")]
    unsafe extern "C" fn export_on_cardano_immutable_roll_forward(arg0: i32,arg1: i32,) {
      unsafe { $($path_to_types)*::_export_on_cardano_immutable_roll_forward_cabi::<$ty>(arg0, arg1) }
    }
  };);
}
#[doc(hidden)]
pub(crate) use __export_event_cabi;

}

}
mod _rt {
  #![allow(dead_code, clippy::all)]
  pub unsafe fn bool_lift(val: u8) -> bool {
    if cfg!(debug_assertions) {
      match val {
        0 => false,
        1 => true,
        _ => panic!("invalid bool discriminant"),
      }
    } else {
      val != 0
    }
  }
  pub use alloc_crate::vec::Vec;

  pub fn as_i32<T: AsI32>(t: T) -> i32 {
    t.as_i32()
  }

  pub trait AsI32 {
    fn as_i32(self) -> i32;
  }

  impl<'a, T: Copy + AsI32> AsI32 for &'a T {
    fn as_i32(self) -> i32 {
      (*self).as_i32()
    }
  }
  
  impl AsI32 for i32 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for u32 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for i16 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for u16 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for i8 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for u8 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for char {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for usize {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  pub unsafe fn invalid_enum_discriminant<T>() -> T {
    if cfg!(debug_assertions) {
      panic!("invalid enum discriminant")
    } else {
      unsafe { core::hint::unreachable_unchecked() }
    }
  }
  

  use core::fmt;
  use core::marker;
  use core::sync::atomic::{AtomicU32, Ordering::Relaxed};

  /// A type which represents a component model resource, either imported or
  /// exported into this component.
  ///
  /// This is a low-level wrapper which handles the lifetime of the resource
  /// (namely this has a destructor). The `T` provided defines the component model
  /// intrinsics that this wrapper uses.
  ///
  /// One of the chief purposes of this type is to provide `Deref` implementations
  /// to access the underlying data when it is owned.
  ///
  /// This type is primarily used in generated code for exported and imported
  /// resources.
  #[repr(transparent)]
  pub struct Resource<T: WasmResource> {
    // NB: This would ideally be `u32` but it is not. The fact that this has
    // interior mutability is not exposed in the API of this type except for the
    // `take_handle` method which is supposed to in theory be private.
    //
    // This represents, almost all the time, a valid handle value. When it's
    // invalid it's stored as `u32::MAX`.
    handle: AtomicU32,
    _marker: marker::PhantomData<T>,
  }

  /// A trait which all wasm resources implement, namely providing the ability to
  /// drop a resource.
  ///
  /// This generally is implemented by generated code, not user-facing code.
  #[allow(clippy::missing_safety_doc)]
  pub unsafe trait WasmResource {
    /// Invokes the `[resource-drop]...` intrinsic.
    unsafe fn drop(handle: u32);
  }

  impl<T: WasmResource> Resource<T> {
    #[doc(hidden)]
    pub unsafe fn from_handle(handle: u32) -> Self {
      debug_assert!(handle != 0 && handle != u32::MAX);
      Self {
        handle: AtomicU32::new(handle),
        _marker: marker::PhantomData,
      }
    }

    /// Takes ownership of the handle owned by `resource`.
    ///
    /// Note that this ideally would be `into_handle` taking `Resource<T>` by
    /// ownership. The code generator does not enable that in all situations,
    /// unfortunately, so this is provided instead.
    ///
    /// Also note that `take_handle` is in theory only ever called on values
    /// owned by a generated function. For example a generated function might
    /// take `Resource<T>` as an argument but then call `take_handle` on a
    /// reference to that argument. In that sense the dynamic nature of
    /// `take_handle` should only be exposed internally to generated code, not
    /// to user code.
    #[doc(hidden)]
    pub fn take_handle(resource: &Resource<T>) -> u32 {
      resource.handle.swap(u32::MAX, Relaxed)
    }

    #[doc(hidden)]
    pub fn handle(resource: &Resource<T>) -> u32 {
      resource.handle.load(Relaxed)
    }
  }

  impl<T: WasmResource> fmt::Debug for Resource<T> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
      f.debug_struct("Resource")
      .field("handle", &self.handle)
      .finish()
    }
  }

  impl<T: WasmResource> Drop for Resource<T> {
    fn drop(&mut self) {
      unsafe {
        match self.handle.load(Relaxed) {
          // If this handle was "taken" then don't do anything in the
          // destructor.
          u32::MAX => {}

          // ... but otherwise do actually destroy it with the imported
          // component model intrinsic as defined through `T`.
          other => T::drop(other),
        }
      }
    }
  }
  
  pub fn as_i64<T: AsI64>(t: T) -> i64 {
    t.as_i64()
  }

  pub trait AsI64 {
    fn as_i64(self) -> i64;
  }

  impl<'a, T: Copy + AsI64> AsI64 for &'a T {
    fn as_i64(self) -> i64 {
      (*self).as_i64()
    }
  }
  
  impl AsI64 for i64 {
    #[inline]
    fn as_i64(self) -> i64 {
      self as i64
    }
  }
  
  impl AsI64 for u64 {
    #[inline]
    fn as_i64(self) -> i64 {
      self as i64
    }
  }
  
  #[cfg(target_arch = "wasm32")]
  pub fn run_ctors_once() {
    wit_bindgen::rt::run_ctors_once();
  }
  extern crate alloc as alloc_crate;
}

/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]

macro_rules! __export_stub_impl {
  ($ty:ident) => (self::export!($ty with_types_in self););
  ($ty:ident with_types_in $($path_to_types_root:tt)*) => (
  $($path_to_types_root)*::exports::event::__export_event_cabi!($ty with_types_in $($path_to_types_root)*::exports::event);
  )
}
#[doc(inline)]
pub(crate) use __export_stub_impl as export;

#[cfg(target_arch = "wasm32")]
#[unsafe(link_section = "component-type:wit-bindgen:0.44.0:hermes:stub:stub:encoded world")]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 2429] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\x82\x12\x01A\x02\x01\
A\x16\x01B\x02\x01@\0\0\x7f\x04\0\x04init\x01\0\x03\0\x11hermes:init/event\x05\0\
\x01B\x08\x01p}\x04\0\x04bstr\x03\0\0\x01o\x02ww\x04\0\x04b128\x03\0\x02\x01o\x04\
wwww\x04\0\x04b256\x03\0\x04\x01o\x08wwwwwwww\x04\0\x04b512\x03\0\x06\x03\0\x11h\
ermes:binary/api\x05\x01\x02\x03\0\x01\x04bstr\x02\x03\0\x01\x04b256\x01B\x12\x02\
\x03\x02\x01\x02\x04\0\x04bstr\x03\0\0\x02\x03\x02\x01\x03\x04\0\x04b256\x03\0\x02\
\x04\0\x0ablake2b256\x03\0\x03\x01m\x05\x0bkey-too-big\x0chash-too-big\x0csalt-t\
oo-big\x10personal-too-big\x1ainvalid-digest-byte-length\x04\0\x05errno\x03\0\x05\
\x01k}\x01j\x01\x01\x01\x06\x01@\x02\x03buf\x01\x06outlen\x07\0\x08\x04\0\x07bla\
ke2s\x01\x09\x01k\x01\x01@\x05\x03buf\x01\x06outlen\x07\x03key\x01\x04salt\x0a\x08\
personal\x0a\0\x08\x04\0\x0ablake2smac\x01\x0b\x04\0\x07blake2b\x01\x09\x04\0\x0a\
blake2bmac\x01\x0b\x01@\x03\x03buf\x01\x06outlen\x07\x03key\x0a\0\x08\x04\0\x06b\
lake3\x01\x0c\x03\0\x0fhermes:hash/api\x05\x04\x01B\x03\x02\x03\x02\x01\x02\x04\0\
\x04bstr\x03\0\0\x04\0\x04cbor\x03\0\x01\x03\0\x0fhermes:cbor/api\x05\x05\x02\x03\
\0\x02\x0ablake2b256\x02\x03\0\x03\x04cbor\x01BG\x02\x03\x02\x01\x06\x04\0\x0abl\
ake2b256\x03\0\0\x02\x03\x02\x01\x07\x04\0\x04cbor\x03\0\x02\x01w\x04\0\x04slot\x03\
\0\x04\x01{\x04\0\x07txn-idx\x03\0\x06\x04\0\x08txn-hash\x03\0\x01\x01q\x04\x07m\
ainnet\0\0\x07preprod\0\0\x07preview\0\0\x0dtestnet-magic\x01y\0\x04\0\x0fcardan\
o-network\x03\0\x09\x01q\x04\x07genesis\0\0\x08specific\x01\x05\0\x03tip\0\0\x0d\
immutable-tip\0\0\x04\0\x09sync-slot\x03\0\x0b\x01m\x01\x12invalid-start-slot\x04\
\0\x0fsubscribe-error\x03\0\x0d\x01m\x01\x15network-not-supported\x04\0\x14creat\
e-network-error\x03\0\x0f\x01m\x01\x0fblock-not-found\x04\0\x0bblock-error\x03\0\
\x11\x01m\x01\x0dtxn-not-found\x04\0\x11transaction-error\x03\0\x13\x04\0\x07net\
work\x03\x01\x04\0\x05block\x03\x01\x04\0\x0btransaction\x03\x01\x04\0\x0fsubscr\
iption-id\x03\x01\x01i\x15\x01j\x01\x19\x01\x10\x01@\x01\x07network\x0a\0\x1a\x04\
\0\x13[static]network.new\x01\x1b\x01h\x15\x01j\x01y\x01\x0e\x01@\x02\x04self\x1c\
\x05start\x0c\0\x1d\x04\0\x1f[method]network.subscribe-block\x01\x1e\x04\00[meth\
od]network.subscribe-immutable-roll-forward\x01\x1e\x01k\x05\x01i\x16\x01k\x20\x01\
@\x03\x04self\x1c\x05start\x1f\x04stepx\0!\x04\0\x19[method]network.get-block\x01\
\"\x01o\x02\x05\x05\x01k#\x01@\x01\x04self\x1c\0$\x04\0\x18[method]network.get-t\
ips\x01%\x01h\x16\x01@\x01\x04self&\0\x7f\x04\0\x1a[method]block.is-immutable\x01\
'\x01j\x01\x7f\x01\x12\x01@\x01\x04self&\0(\x04\0\x19[method]block.is-rollback\x01\
)\x01i\x17\x01j\x01*\x01\x14\x01@\x02\x04self&\x05index\x07\0+\x04\0\x15[method]\
block.get-txn\x01,\x01@\x01\x04self&\0\x05\x04\0\x16[method]block.get-slot\x01-\x01\
@\x01\x04self&\0\x03\x04\0\x11[method]block.raw\x01.\x01h\x17\x01k\x03\x01@\x02\x04\
self/\x05labelw\00\x04\0\x20[method]transaction.get-metadata\x011\x01k\x08\x01@\x01\
\x04self/\02\x04\0\x20[method]transaction.get-txn-hash\x013\x01@\x01\x04self/\00\
\x04\0\x17[method]transaction.raw\x014\x01h\x18\x01@\x01\x04self5\0\x0a\x04\0#[m\
ethod]subscription-id.get-network\x016\x01@\x01\x04self5\x01\0\x04\0#[method]sub\
scription-id.unsubscribe\x017\x03\0\x12hermes:cardano/api\x05\x08\x02\x03\0\x04\x05\
block\x02\x03\0\x04\x0fsubscription-id\x01B\x0a\x02\x03\x02\x01\x09\x04\0\x05blo\
ck\x03\0\0\x02\x03\x02\x01\x0a\x04\0\x0fsubscription-id\x03\0\x02\x02\x03\x02\x01\
\x07\x04\0\x04cbor\x03\0\x04\x01h\x03\x01h\x01\x01@\x02\x0fsubscription-id\x06\x05\
block\x07\x01\0\x04\0\x10on-cardano-block\x01\x08\x03\0\x1dhermes:cardano/event-\
on-block\x05\x0b\x01B\x08\x02\x03\x02\x01\x09\x04\0\x05block\x03\0\0\x02\x03\x02\
\x01\x0a\x04\0\x0fsubscription-id\x03\0\x02\x01h\x03\x01h\x01\x01@\x02\x0fsubscr\
iption-id\x04\x05block\x05\x01\0\x04\0!on-cardano-immutable-roll-forward\x01\x06\
\x03\0.hermes:cardano/event-on-immutable-roll-forward\x05\x0c\x01B\x0d\x02\x03\x02\
\x01\x09\x04\0\x05block\x03\0\0\x02\x03\x02\x01\x0a\x04\0\x0fsubscription-id\x03\
\0\x02\x02\x03\x02\x01\x07\x04\0\x04cbor\x03\0\x04\x01@\0\0\x7f\x04\0\x04init\x01\
\x06\x01h\x03\x01h\x01\x01@\x02\x0fsubscription-id\x07\x05block\x08\x01\0\x04\0\x10\
on-cardano-block\x01\x09\x04\0!on-cardano-immutable-roll-forward\x01\x09\x04\0\x05\
event\x05\x0d\x04\0\x10hermes:stub/stub\x04\0\x0b\x0a\x01\0\x04stub\x03\0\0\0G\x09\
producers\x01\x0cprocessed-by\x02\x0dwit-component\x070.236.1\x10wit-bindgen-rus\
t\x060.44.0";

#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
  wit_bindgen::rt::maybe_link_cabi_realloc();
}

