// Generated by `wit-bindgen` 0.44.0. DO NOT EDIT!
#ifndef __BINDINGS_STUB_H
#define __BINDINGS_STUB_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

// Binary String (bstr) is a list of bytes.
//    This type is used to indicate the data is an arbitrary array of bytes.
typedef struct hermes_binary_api_bstr_t {
  uint8_t   *ptr;
  size_t len;
} hermes_binary_api_bstr_t;

// 128 bit value
typedef struct hermes_binary_api_b128_t {
  uint64_t   f0;
  uint64_t   f1;
} hermes_binary_api_b128_t;

// 256 bit value
typedef struct hermes_binary_api_b256_t {
  uint64_t   f0;
  uint64_t   f1;
  uint64_t   f2;
  uint64_t   f3;
} hermes_binary_api_b256_t;

// 512 bit value
typedef struct hermes_binary_api_b512_t {
  uint64_t   f0;
  uint64_t   f1;
  uint64_t   f2;
  uint64_t   f3;
  uint64_t   f4;
  uint64_t   f5;
  uint64_t   f6;
  uint64_t   f7;
} hermes_binary_api_b512_t;

typedef hermes_binary_api_bstr_t hermes_hash_api_bstr_t;

typedef hermes_binary_api_b256_t hermes_hash_api_b256_t;

// A 256-bit (32-byte) cryptographic hash value produced by the BLAKE2b hash function.
typedef hermes_hash_api_b256_t hermes_hash_api_blake2b256_t;

// Errors that can occur during hashing.
typedef uint8_t hermes_hash_api_errno_t;

#define HERMES_HASH_API_ERRNO_KEY_TOO_BIG 0
// The key exceeds the supported size of the hash function.
#define HERMES_HASH_API_ERRNO_HASH_TOO_BIG 1
// The hash size requested is larger than supported by the hash function.
#define HERMES_HASH_API_ERRNO_SALT_TOO_BIG 2
// The salt exceeds the supported size of the hash function.
#define HERMES_HASH_API_ERRNO_PERSONAL_TOO_BIG 3
// The personal exceeds the supported size of the hash function.
#define HERMES_HASH_API_ERRNO_INVALID_DIGEST_BYTE_LENGTH 4

typedef struct {
  bool is_some;
  uint8_t val;
} stub_option_u8_t;

typedef struct {
  bool is_err;
  union {
    hermes_hash_api_bstr_t ok;
    hermes_hash_api_errno_t err;
  } val;
} hermes_hash_api_result_bstr_errno_t;

typedef struct {
  bool is_some;
  hermes_hash_api_bstr_t val;
} stub_option_bstr_t;

typedef hermes_binary_api_bstr_t hermes_cbor_api_bstr_t;

// CBOR is a binary cbor data type.
//    This type is used to indicate the binary array MUST be CBOR data.
typedef hermes_cbor_api_bstr_t hermes_cbor_api_cbor_t;

typedef hermes_hash_api_blake2b256_t hermes_cardano_api_blake2b256_t;

typedef hermes_cbor_api_cbor_t hermes_cardano_api_cbor_t;

// Slot on the Cardano blockchain.
typedef uint64_t hermes_cardano_api_slot_t;

// Cardano transaction index.
typedef uint16_t hermes_cardano_api_txn_idx_t;

// Cardano transaction hash.
typedef hermes_cardano_api_blake2b256_t hermes_cardano_api_txn_hash_t;

// Cardano blockchain network.
typedef struct hermes_cardano_api_cardano_network_t {
  uint8_t tag;
  union {
    uint32_t     testnet_magic;
  } val;
} hermes_cardano_api_cardano_network_t;

// Cardano Mainnet Network :- "NetworkId": 1, "NetworkMagic": 764824073
#define HERMES_CARDANO_API_CARDANO_NETWORK_MAINNET 0
// Cardano Preprod Network :- "NetworkId": 0, "NetworkMagic": 1
#define HERMES_CARDANO_API_CARDANO_NETWORK_PREPROD 1
// Cardano Preview Network :- "NetworkId": 0, "NetworkMagic": 2
#define HERMES_CARDANO_API_CARDANO_NETWORK_PREVIEW 2
// Custom Test Network :- "NetworkId": 0,  "NetworkMagic": u32
#define HERMES_CARDANO_API_CARDANO_NETWORK_TESTNET_MAGIC 3

// A sync slot variation.
typedef struct hermes_cardano_api_sync_slot_t {
  uint8_t tag;
  union {
    hermes_cardano_api_slot_t     specific;
  } val;
} hermes_cardano_api_sync_slot_t;

// Genesis (first block) of the blockchain.
#define HERMES_CARDANO_API_SYNC_SLOT_GENESIS 0
// A specific slot in the blockchain.
#define HERMES_CARDANO_API_SYNC_SLOT_SPECIFIC 1
// The live tip of the blockchain, following the upstream node.
#define HERMES_CARDANO_API_SYNC_SLOT_TIP 2
// The immutable tip of the blockchain
// e.g., The last block which has reached the absolute finality and can never rolls back.
#define HERMES_CARDANO_API_SYNC_SLOT_IMMUTABLE_TIP 3

// Errors that can happen for subscribing to blocks
typedef uint8_t hermes_cardano_api_subscribe_error_t;

// The slot requested is not valid.
#define HERMES_CARDANO_API_SUBSCRIBE_ERROR_INVALID_START_SLOT 0

// Errors that can happen when initialize network.
typedef uint8_t hermes_cardano_api_create_network_error_t;

// Network not supported.
#define HERMES_CARDANO_API_CREATE_NETWORK_ERROR_NETWORK_NOT_SUPPORTED 0

// Errors that can happen for block.
typedef uint8_t hermes_cardano_api_block_error_t;

// Block is not found.
#define HERMES_CARDANO_API_BLOCK_ERROR_BLOCK_NOT_FOUND 0

// Errors that can happen for transaction.
typedef uint8_t hermes_cardano_api_transaction_error_t;

// Transaction not found
#define HERMES_CARDANO_API_TRANSACTION_ERROR_TXN_NOT_FOUND 0

typedef struct hermes_cardano_api_own_network_t {
  int32_t __handle;
} hermes_cardano_api_own_network_t;

typedef struct hermes_cardano_api_borrow_network_t {
  int32_t __handle;
} hermes_cardano_api_borrow_network_t;

typedef struct hermes_cardano_api_own_block_t {
  int32_t __handle;
} hermes_cardano_api_own_block_t;

typedef struct hermes_cardano_api_borrow_block_t {
  int32_t __handle;
} hermes_cardano_api_borrow_block_t;

typedef struct hermes_cardano_api_own_transaction_t {
  int32_t __handle;
} hermes_cardano_api_own_transaction_t;

typedef struct hermes_cardano_api_borrow_transaction_t {
  int32_t __handle;
} hermes_cardano_api_borrow_transaction_t;

typedef struct hermes_cardano_api_own_subscription_id_t {
  int32_t __handle;
} hermes_cardano_api_own_subscription_id_t;

typedef struct hermes_cardano_api_borrow_subscription_id_t {
  int32_t __handle;
} hermes_cardano_api_borrow_subscription_id_t;

typedef struct {
  bool is_err;
  union {
    hermes_cardano_api_own_network_t ok;
    hermes_cardano_api_create_network_error_t err;
  } val;
} hermes_cardano_api_result_own_network_create_network_error_t;

typedef struct {
  bool is_err;
  union {
    uint32_t ok;
    hermes_cardano_api_subscribe_error_t err;
  } val;
} hermes_cardano_api_result_u32_subscribe_error_t;

typedef struct {
  bool is_some;
  hermes_cardano_api_slot_t val;
} stub_option_slot_t;

typedef struct {
  bool is_some;
  hermes_cardano_api_own_block_t val;
} hermes_cardano_api_option_own_block_t;

typedef struct {
  hermes_cardano_api_slot_t f0;
  hermes_cardano_api_slot_t f1;
} stub_tuple2_slot_slot_t;

typedef struct {
  bool is_some;
  stub_tuple2_slot_slot_t val;
} stub_option_tuple2_slot_slot_t;

typedef struct {
  bool is_err;
  union {
    bool ok;
    hermes_cardano_api_block_error_t err;
  } val;
} hermes_cardano_api_result_bool_block_error_t;

typedef struct {
  bool is_err;
  union {
    hermes_cardano_api_own_transaction_t ok;
    hermes_cardano_api_transaction_error_t err;
  } val;
} hermes_cardano_api_result_own_transaction_transaction_error_t;

typedef struct {
  bool is_some;
  hermes_cardano_api_cbor_t val;
} stub_option_cbor_t;

typedef struct {
  bool is_some;
  hermes_cardano_api_txn_hash_t val;
} stub_option_txn_hash_t;

typedef hermes_cbor_api_cbor_t hermes_cardano_event_on_block_cbor_t;

typedef hermes_cardano_api_borrow_subscription_id_t hermes_cardano_event_on_block_borrow_subscription_id_t;

typedef hermes_cardano_api_borrow_block_t hermes_cardano_event_on_block_borrow_block_t;

typedef hermes_cardano_api_borrow_subscription_id_t hermes_cardano_event_on_immutable_roll_forward_borrow_subscription_id_t;

typedef hermes_cardano_api_borrow_block_t hermes_cardano_event_on_immutable_roll_forward_borrow_block_t;

typedef hermes_cbor_api_cbor_t event_cbor_t;

typedef hermes_cardano_api_borrow_subscription_id_t event_borrow_subscription_id_t;

typedef hermes_cardano_api_borrow_block_t event_borrow_block_t;

// Imported Functions from `hermes:init/event`
// Perform application start up initialization.
// 
// This will only ever be called once when the application this module is a part of is started.
// The module must export this interface to use it.
// 
// Returns:
// - `true`  - Initialization is successful, the application may commence.
// - `false` - Fatal error during Initialization.  DO NOT START APPLICATION.
extern bool hermes_init_event_init(void);

// Imported Functions from `hermes:hash/api`
// # BLAKE2s Hash Function
// 
// Hash a binary buffer with BLAKE2s.
// 
// ## Parameters
// 
// - `buf`: The binary data buffer to hash.
// - `outlen`: Optional.  The size of the digest.
//             If the outlen is not defined, it defaults to 32.
// 
// ## Returns
// 
// - Either a buffer the size requested, with the hash.
// - Or an error:
//     - `hash_too_big` if `outlen` is specified and is > 32 bytes.
//     - `invalid_digest_byte_length` if `outlen` is specified and is = 0.
extern bool hermes_hash_api_blake2s(hermes_hash_api_bstr_t *buf, uint8_t *maybe_outlen, hermes_hash_api_bstr_t *ret, hermes_hash_api_errno_t *err);
// # BLAKE2sMac Hash Function
// 
// Hash a binary buffer with BLAKE2s with MAC (Message Authentication Code) mode.
// 
// ## Parameters
// 
// - `buf`: The binary data buffer to hash.
// - `outlen`: Optional.  The size of the digest.
//             If the outlen is not defined, it defaults to 32.
// - `key`: The key to use with the hash.
//             With MAC mode, key is needed to be defined
//             Should not be > 32 bytes.
// - `salt`: Optional. Salt uses to increase the randomness and
//             uniqueness of the hash output
//             Should not be > 8 bytes.
//             If not defined, salt is not used.
// - `personal`: Optional. Personal allows to
//             add customization to the hash function behavior.
//             Should not be > 8 bytes.
//             If not defined, personal is not used.
// 
// ## Returns
// 
// - Either a buffer the size requested, with the hash.
// - Or an error:
//     - `key_too_big` if `key` is > 32 bytes.
//     - `hash_too_big` if `outlen` is specified and is > 32 bytes.
//     - `salt_too_big` if `salt` is specified and is > 8 bytes.
//     - `personal_too_big` if `personal` is specified and is > 8 bytes.
// 
// ## Note:
// 
// `key` length is checked before `outlen` so if both sizes are invalid, only
// `key_too_big` will be returned.
// If `salt` length exceeds 8 bytes, `salt_too_big` will be returned.
// if `personal` length exceeds 8 bytes, `personal_too_big` will be returned.
extern bool hermes_hash_api_blake2smac(hermes_hash_api_bstr_t *buf, uint8_t *maybe_outlen, hermes_hash_api_bstr_t *key, hermes_hash_api_bstr_t *maybe_salt, hermes_hash_api_bstr_t *maybe_personal, hermes_hash_api_bstr_t *ret, hermes_hash_api_errno_t *err);
// # BLAKE2b Hash Function
// 
// Hash a binary buffer with BLAKE2b.
// 
// ## Parameters
// 
// - `buf`: The binary data buffer to hash.
// - `outlen`: Optional. The size of the digest.
//             If the outlen is not defined, it defaults to 64.
// 
// ## Returns
// 
// - Either a buffer the size requested, with the hash.
// - Or an error:
//     - `hash_too_big` if `outlen` is specified and is > 64 bytes.
//     - `invalid_digest_byte_length` if `outlen` is specified and is = 0.
extern bool hermes_hash_api_blake2b(hermes_hash_api_bstr_t *buf, uint8_t *maybe_outlen, hermes_hash_api_bstr_t *ret, hermes_hash_api_errno_t *err);
// # BLAKE2bMac Hash Function
// 
// Hash a binary buffer with BLAKE2b with MAC (Message Authentication Code) mode.
// 
// ## Parameters
// 
// - `buf`: The binary data buffer to hash.
// - `outlen`: Optional.  The size of the digest.
//             If the outlen is not defined, it defaults to 64.
// - `key`: The key to use with the hash.
//             With MAC mode, key is needed to be defined
//             Should not be > 64 bytes.
// - `salt`: Optional. Salt uses to increase the randomness and
//             uniqueness of the hash output
//             Should not be > 16 bytes.
//             If not defined, salt is not used.
// - `personal`: Optional. Personal allows to
//             add customization to the hash function behavior.
//             Should not be > 16 bytes.
//             If not defined, personal is not used.
// 
// ## Returns
// 
// - Either a buffer the size requested, with the hash.
// - Or an error:
//     - `key_too_big` if `key` is specified and is > 64 bytes.
//     - `hash_too_big` if `outlen` is specified and is > 64 bytes.
//     - `salt_too_big` if `salt` is specified and is > 16 bytes.
//     - `personal_too_big` if `personal` is specified and is > 16 bytes.
// 
// ## Note:
// 
// `key` length is checked before `outlen` so if both sizes are invalid, only
// `key_too_big` will be returned.
// If `salt` length exceeds 16 bytes, `salt_too_big` will be returned.
// if `personal` length exceeds 16 bytes, `personal_too_big` will be returned.
extern bool hermes_hash_api_blake2bmac(hermes_hash_api_bstr_t *buf, uint8_t *maybe_outlen, hermes_hash_api_bstr_t *key, hermes_hash_api_bstr_t *maybe_salt, hermes_hash_api_bstr_t *maybe_personal, hermes_hash_api_bstr_t *ret, hermes_hash_api_errno_t *err);
// # BLAKE3 Hash Function
// 
// Hash a binary buffer with BLAKE3.
// 
// ## Parameters
// 
// - `buf`: The binary data buffer to hash.
// - `outlen`: Optional.  The size of the digest.
//             If the outlen is not defined, it defaults to 32.
// - `key`: Optional. The key to use with the hash.
//             If not defined, the hash is not keyed.
//             Should not be > 32 bytes.
// 
// ## Returns
// 
// - Either a buffer the size requested, with the hash.
// - Or an error:
//     - `key_too_big` if `key` is specified and is > 32 bytes.
//     - `hash_too_big` if `outlen` is specified and is > 32 bytes.
// 
// ## Note:
// 
// `key` length is checked before `outlen` so if both sizes are invalid, only
// `key_too_big` will be returned.
extern bool hermes_hash_api_blake3(hermes_hash_api_bstr_t *buf, uint8_t *maybe_outlen, hermes_hash_api_bstr_t *maybe_key, hermes_hash_api_bstr_t *ret, hermes_hash_api_errno_t *err);

// Imported Functions from `hermes:cardano/api`
// Create a new Cardano network instance.
// 
// **Parameters**
// 
// - `network`: The Cardano network to connect to (e.g., Mainnet, Preprod, Preview).
// 
// **Returns**
// 
// - `ok(network)`: A resource network, if successfully create network resource.
// - `error(create-network-error)`: If creating network resource failed.
extern bool hermes_cardano_api_static_network_new(hermes_cardano_api_cardano_network_t *network, hermes_cardano_api_own_network_t *ret, hermes_cardano_api_create_network_error_t *err);
// Subscribe to blockchain block events, start from a specified starting point.
// 
// This sets up a subscription to receive new block and block rollback updates starting from the
// given `start`.
// 
// **Parameters**
// 
// - `start`: The slot to begin following from.
// 
// **Returns**
// 
// - `ok(u32)`: A unsigned integer represent the underlying 32-bit representation of subscription ID
//              resource. this subscription. Use to distinguishes events from different subscribers
//              and provides control over subscription management.The ID must be unique across all
//              active subscriptions.
// - `error(subscribe-error)`: If subscription failed.
extern bool hermes_cardano_api_method_network_subscribe_block(hermes_cardano_api_borrow_network_t self, hermes_cardano_api_sync_slot_t *start, uint32_t *ret, hermes_cardano_api_subscribe_error_t *err);
// Subscribe to blockchain immutable rolls forward.
// 
// This sets up a subscription to receive event when the immutable part of the blockchain
// roll forwards.
// 
// **Parameters**
// 
// - `start`: The slot to begin following from.
// 
// **Returns**
// 
// - `ok(u32)`: A unsigned integer represent the underlying 32-bit representation of subscription ID
//              resource. this subscription. Use to distinguishes events from different subscribers
//              and provides control over subscription management.The ID must be unique across all
//              active subscriptions.
// - `error(subscribe-error)`: If subscription failed.
extern bool hermes_cardano_api_method_network_subscribe_immutable_roll_forward(hermes_cardano_api_borrow_network_t self, hermes_cardano_api_sync_slot_t *start, uint32_t *ret, hermes_cardano_api_subscribe_error_t *err);
// Get a block relative to `start` by `step`.
// 
// **Parameters**
// - `start`: Slot to begin retrieval from, current tip if `None`.
// - `step`
//     -`0` : the block at `start`, will return `None` if there is no block exactly at this `start` slot.
//     -`+n`: the `n`‑th block *after* the given `start` slot.
//     –`‑n`: the `n`‑th block *before* the given `start` slot.
// 
// Note: For both `+n` and `-n`, the `start` does not need to be a true block.
// They will return the block which appears at this block offset, given the arbitrary start point.
// IF the `start` block does exist, it will never returned with a positive or negative `step`, as it is `step` 0.
// 
// Example, Given three consecutive blocks at slots `100`, `200` and `300` the following will be returned:
//     - `start = 100, step = 0` -> 100 (Exact match)
//     - `start = 100, step = 2` -> 300 (Skips 200)
//     - `start = 150, step = 1` -> 200 (Rounds up from 150)
//     - `start = 200, step = 1` -> 300 (Forward iteration)
//     - `start = 300, step = -2` -> 100 (Skips 200)
//     - `start = 250, step = -2` -> 100 (Rounds down to 200 first)
// 
// **Returns**
// 
// - Returns a `block` resource, `None` if block cannot be retrieved.
extern bool hermes_cardano_api_method_network_get_block(hermes_cardano_api_borrow_network_t self, hermes_cardano_api_slot_t *maybe_start, int64_t step, hermes_cardano_api_own_block_t *ret);
// Retrieve the current tips of the blockchain.
// 
// **Returns**
// 
// - A tuple of two slots:
//   - The immutable tip.
//   - The mutable tip.
// `None` if the tips cannot be retrieved.
extern bool hermes_cardano_api_method_network_get_tips(hermes_cardano_api_borrow_network_t self, stub_tuple2_slot_slot_t *ret);
// Returns whether the block is part of the immutable section of the chain.
// 
// **Returns**
// 
// - `true` if the block is in the immutable part.
// - `false` if the block is in the mutable part.
extern bool hermes_cardano_api_method_block_is_immutable(hermes_cardano_api_borrow_block_t self);
// Returns whether the block is the first block of a rollback.
// 
// **Returns**
// 
// - `ok(bool)` True if the block is the first block of a rollback,
//              otherwise, False.
// - `error(block-error)`: If block cannot be retrieved.
extern bool hermes_cardano_api_method_block_is_rollback(hermes_cardano_api_borrow_block_t self, bool *ret, hermes_cardano_api_block_error_t *err);
// Retrieves a transaction at the specified index within the block.
// 
// **Parameters**
// 
// - `index` : The index of the transaction to retrieve.
// 
// **Returns**
// 
// - `ok(transaction)` : A `transaction` resource at the given index
// - `error(transaction-error)`: If a transaction data does not exist in the block at the given index.
extern bool hermes_cardano_api_method_block_get_txn(hermes_cardano_api_borrow_block_t self, hermes_cardano_api_txn_idx_t index, hermes_cardano_api_own_transaction_t *ret, hermes_cardano_api_transaction_error_t *err);
// Retrieves the slot number that this block belongs to.
// 
// **Returns**
// 
// - `slot` : The slot number of the block.
extern hermes_cardano_api_slot_t hermes_cardano_api_method_block_get_slot(hermes_cardano_api_borrow_block_t self);
// Returns the raw CBOR representation of the block.
// 
// **Returns**
// 
// - `cbor` : The CBOR format of the block.
extern void hermes_cardano_api_method_block_raw(hermes_cardano_api_borrow_block_t self, hermes_cardano_api_cbor_t *ret);
// Returns the transaction auxiliary metadata in CBOR format.
// 
// **Parameters**
// 
// - `label`: A metadata label used as a key to get the associated metadata.
// 
// **Returns**
// 
// - `option<cbor>` : The CBOR format of the metadata, `None` if the label requested is not present.
extern bool hermes_cardano_api_method_transaction_get_metadata(hermes_cardano_api_borrow_transaction_t self, uint64_t label, hermes_cardano_api_cbor_t *ret);
// Returns the transaction hash.
// 
// **Returns**
// 
// - `option<txn-hash>` : Cardano transaction hash - Blake2b-256, `None` if cannot retrieve the transaction hash.
extern bool hermes_cardano_api_method_transaction_get_txn_hash(hermes_cardano_api_borrow_transaction_t self, hermes_cardano_api_txn_hash_t *ret);
// Returns the raw CBOR representation of the transaction.
// 
// **Returns**
// 
// - `option<cbor>` : The CBOR format of the transaction, `None` if cannot retrieve the raw transaction.
extern bool hermes_cardano_api_method_transaction_raw(hermes_cardano_api_borrow_transaction_t self, hermes_cardano_api_cbor_t *ret);
// Returns the network that this subscription is in.
// 
// **Returns**
// 
// - `cardano-network` : The Cardano network that this subscription is in.
extern void hermes_cardano_api_method_subscription_id_get_network(hermes_cardano_api_borrow_subscription_id_t self, hermes_cardano_api_cardano_network_t *ret);
// Unsubscribing block event of this `subscription-id` instance.
// Once this function is called, the subscription instance, `subscription-id` will be removed.
extern void hermes_cardano_api_method_subscription_id_unsubscribe(hermes_cardano_api_borrow_subscription_id_t self);

// Imported Functions from `hermes:cardano/event-on-block`
// Trigger when a Cardano block event is fired.
// 
// 
// ## Parameters
// 
// - `subscription-id` : A unique identifier of the block subscription.
// - `block` : A block resource where information of the block can be retrieve.
extern void hermes_cardano_event_on_block_on_cardano_block(hermes_cardano_event_on_block_borrow_subscription_id_t subscription_id, hermes_cardano_event_on_block_borrow_block_t block);

// Imported Functions from `hermes:cardano/event-on-immutable-roll-forward`
// Trigger when a Cardano immutable roll-forward event is fired.
// 
// ## Parameters
// 
// - `subscription-id` : A unique identifier of the block subscription.
// - `block` : A block resource where information of the block can be retrieve.
// 
// ## Notes
// 
// Roll-forward events are guaranteed to be fully processed **before** the next
// block event is delivered. The block event delivered immediately after a
// roll-forward will correspond to the block at the roll-forward target `slot`.
// This means that roll-forward processing **does not** need to reset or re-subscribe the blockchain follower.
extern void hermes_cardano_event_on_immutable_roll_forward_on_cardano_immutable_roll_forward(hermes_cardano_event_on_immutable_roll_forward_borrow_subscription_id_t subscription_id, hermes_cardano_event_on_immutable_roll_forward_borrow_block_t block);

// Exported Functions from `event`
bool event_init(void);
void event_on_cardano_block(event_borrow_subscription_id_t subscription_id, event_borrow_block_t block);
void event_on_cardano_immutable_roll_forward(event_borrow_subscription_id_t subscription_id, event_borrow_block_t block);

// Helper Functions

void hermes_binary_api_bstr_free(hermes_binary_api_bstr_t *ptr);

void hermes_hash_api_bstr_free(hermes_hash_api_bstr_t *ptr);

void stub_option_u8_free(stub_option_u8_t *ptr);

void hermes_hash_api_result_bstr_errno_free(hermes_hash_api_result_bstr_errno_t *ptr);

void stub_option_bstr_free(stub_option_bstr_t *ptr);

void hermes_cbor_api_bstr_free(hermes_cbor_api_bstr_t *ptr);

void hermes_cbor_api_cbor_free(hermes_cbor_api_cbor_t *ptr);

void hermes_cardano_api_cbor_free(hermes_cardano_api_cbor_t *ptr);

void hermes_cardano_api_cardano_network_free(hermes_cardano_api_cardano_network_t *ptr);

void hermes_cardano_api_sync_slot_free(hermes_cardano_api_sync_slot_t *ptr);

extern void hermes_cardano_api_network_drop_own(hermes_cardano_api_own_network_t handle);

extern hermes_cardano_api_borrow_network_t hermes_cardano_api_borrow_network(hermes_cardano_api_own_network_t handle);

extern void hermes_cardano_api_block_drop_own(hermes_cardano_api_own_block_t handle);

extern hermes_cardano_api_borrow_block_t hermes_cardano_api_borrow_block(hermes_cardano_api_own_block_t handle);

extern void hermes_cardano_api_transaction_drop_own(hermes_cardano_api_own_transaction_t handle);

extern hermes_cardano_api_borrow_transaction_t hermes_cardano_api_borrow_transaction(hermes_cardano_api_own_transaction_t handle);

extern void hermes_cardano_api_subscription_id_drop_own(hermes_cardano_api_own_subscription_id_t handle);

extern hermes_cardano_api_borrow_subscription_id_t hermes_cardano_api_borrow_subscription_id(hermes_cardano_api_own_subscription_id_t handle);

void hermes_cardano_api_result_own_network_create_network_error_free(hermes_cardano_api_result_own_network_create_network_error_t *ptr);

void hermes_cardano_api_result_u32_subscribe_error_free(hermes_cardano_api_result_u32_subscribe_error_t *ptr);

void stub_option_slot_free(stub_option_slot_t *ptr);

void hermes_cardano_api_option_own_block_free(hermes_cardano_api_option_own_block_t *ptr);

void stub_option_tuple2_slot_slot_free(stub_option_tuple2_slot_slot_t *ptr);

void hermes_cardano_api_result_bool_block_error_free(hermes_cardano_api_result_bool_block_error_t *ptr);

void hermes_cardano_api_result_own_transaction_transaction_error_free(hermes_cardano_api_result_own_transaction_transaction_error_t *ptr);

void stub_option_cbor_free(stub_option_cbor_t *ptr);

void stub_option_txn_hash_free(stub_option_txn_hash_t *ptr);

void hermes_cardano_event_on_block_cbor_free(hermes_cardano_event_on_block_cbor_t *ptr);

void event_cbor_free(event_cbor_t *ptr);


#ifdef __cplusplus
}
#endif
#endif
