// Generated by `wit-bindgen` 0.44.0. DO NOT EDIT!
#include "stub.h"
#include <stdlib.h>

// Imported Functions from `hermes:init/event`

__attribute__((__import_module__("hermes:init/event"), __import_name__("init")))
extern int32_t __wasm_import_hermes_init_event_init(void);

// Imported Functions from `hermes:hash/api`

__attribute__((__import_module__("hermes:hash/api"), __import_name__("blake2s")))
extern void __wasm_import_hermes_hash_api_blake2s(uint8_t *, size_t, int32_t, int32_t, uint8_t *);

__attribute__((__import_module__("hermes:hash/api"), __import_name__("blake2smac")))
extern void __wasm_import_hermes_hash_api_blake2smac(uint8_t *, size_t, int32_t, int32_t, uint8_t *, size_t, int32_t, uint8_t *, size_t, int32_t, uint8_t *, size_t, uint8_t *);

__attribute__((__import_module__("hermes:hash/api"), __import_name__("blake2b")))
extern void __wasm_import_hermes_hash_api_blake2b(uint8_t *, size_t, int32_t, int32_t, uint8_t *);

__attribute__((__import_module__("hermes:hash/api"), __import_name__("blake2bmac")))
extern void __wasm_import_hermes_hash_api_blake2bmac(uint8_t *, size_t, int32_t, int32_t, uint8_t *, size_t, int32_t, uint8_t *, size_t, int32_t, uint8_t *, size_t, uint8_t *);

__attribute__((__import_module__("hermes:hash/api"), __import_name__("blake3")))
extern void __wasm_import_hermes_hash_api_blake3(uint8_t *, size_t, int32_t, int32_t, int32_t, uint8_t *, size_t, uint8_t *);

// Imported Functions from `hermes:cardano/api`

__attribute__((__import_module__("hermes:cardano/api"), __import_name__("[static]network.new")))
extern void __wasm_import_hermes_cardano_api_static_network_new(int32_t, int32_t, uint8_t *);

__attribute__((__import_module__("hermes:cardano/api"), __import_name__("[method]network.subscribe-block")))
extern void __wasm_import_hermes_cardano_api_method_network_subscribe_block(int32_t, int32_t, int64_t, uint8_t *);

__attribute__((__import_module__("hermes:cardano/api"), __import_name__("[method]network.subscribe-immutable-roll-forward")))
extern void __wasm_import_hermes_cardano_api_method_network_subscribe_immutable_roll_forward(int32_t, int32_t, int64_t, uint8_t *);

__attribute__((__import_module__("hermes:cardano/api"), __import_name__("[method]network.get-block")))
extern void __wasm_import_hermes_cardano_api_method_network_get_block(int32_t, int32_t, int64_t, int64_t, uint8_t *);

__attribute__((__import_module__("hermes:cardano/api"), __import_name__("[method]network.get-tips")))
extern void __wasm_import_hermes_cardano_api_method_network_get_tips(int32_t, uint8_t *);

__attribute__((__import_module__("hermes:cardano/api"), __import_name__("[method]block.is-immutable")))
extern int32_t __wasm_import_hermes_cardano_api_method_block_is_immutable(int32_t);

__attribute__((__import_module__("hermes:cardano/api"), __import_name__("[method]block.is-rollback")))
extern void __wasm_import_hermes_cardano_api_method_block_is_rollback(int32_t, uint8_t *);

__attribute__((__import_module__("hermes:cardano/api"), __import_name__("[method]block.get-txn")))
extern void __wasm_import_hermes_cardano_api_method_block_get_txn(int32_t, int32_t, uint8_t *);

__attribute__((__import_module__("hermes:cardano/api"), __import_name__("[method]block.get-slot")))
extern int64_t __wasm_import_hermes_cardano_api_method_block_get_slot(int32_t);

__attribute__((__import_module__("hermes:cardano/api"), __import_name__("[method]block.raw")))
extern void __wasm_import_hermes_cardano_api_method_block_raw(int32_t, uint8_t *);

__attribute__((__import_module__("hermes:cardano/api"), __import_name__("[method]transaction.get-metadata")))
extern void __wasm_import_hermes_cardano_api_method_transaction_get_metadata(int32_t, int64_t, uint8_t *);

__attribute__((__import_module__("hermes:cardano/api"), __import_name__("[method]transaction.get-txn-hash")))
extern void __wasm_import_hermes_cardano_api_method_transaction_get_txn_hash(int32_t, uint8_t *);

__attribute__((__import_module__("hermes:cardano/api"), __import_name__("[method]transaction.raw")))
extern void __wasm_import_hermes_cardano_api_method_transaction_raw(int32_t, uint8_t *);

__attribute__((__import_module__("hermes:cardano/api"), __import_name__("[method]subscription-id.get-network")))
extern void __wasm_import_hermes_cardano_api_method_subscription_id_get_network(int32_t, uint8_t *);

__attribute__((__import_module__("hermes:cardano/api"), __import_name__("[method]subscription-id.unsubscribe")))
extern void __wasm_import_hermes_cardano_api_method_subscription_id_unsubscribe(int32_t);

// Imported Functions from `hermes:cardano/event-on-block`

__attribute__((__import_module__("hermes:cardano/event-on-block"), __import_name__("on-cardano-block")))
extern void __wasm_import_hermes_cardano_event_on_block_on_cardano_block(int32_t, int32_t);

// Imported Functions from `hermes:cardano/event-on-immutable-roll-forward`

__attribute__((__import_module__("hermes:cardano/event-on-immutable-roll-forward"), __import_name__("on-cardano-immutable-roll-forward")))
extern void __wasm_import_hermes_cardano_event_on_immutable_roll_forward_on_cardano_immutable_roll_forward(int32_t, int32_t);

// Exported Functions from `event`




// Canonical ABI intrinsics

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Helper Functions

void hermes_binary_api_bstr_free(hermes_binary_api_bstr_t *ptr) {
  size_t list_len = ptr->len;
  if (list_len > 0) {
    uint8_t *list_ptr = ptr->ptr;
    for (size_t i = 0; i < list_len; i++) {
    }
    free(list_ptr);
  }
}

void hermes_hash_api_bstr_free(hermes_hash_api_bstr_t *ptr) {
  hermes_binary_api_bstr_free(ptr);
}

void stub_option_u8_free(stub_option_u8_t *ptr) {
  if (ptr->is_some) {
  }
}

void hermes_hash_api_result_bstr_errno_free(hermes_hash_api_result_bstr_errno_t *ptr) {
  if (!ptr->is_err) {
    hermes_hash_api_bstr_free(&ptr->val.ok);
  } else {
  }
}

void stub_option_bstr_free(stub_option_bstr_t *ptr) {
  if (ptr->is_some) {
    hermes_hash_api_bstr_free(&ptr->val);
  }
}

void hermes_cbor_api_bstr_free(hermes_cbor_api_bstr_t *ptr) {
  hermes_binary_api_bstr_free(ptr);
}

void hermes_cbor_api_cbor_free(hermes_cbor_api_cbor_t *ptr) {
  hermes_cbor_api_bstr_free(ptr);
}

void hermes_cardano_api_cbor_free(hermes_cardano_api_cbor_t *ptr) {
  hermes_cbor_api_cbor_free(ptr);
}

void hermes_cardano_api_cardano_network_free(hermes_cardano_api_cardano_network_t *ptr) {
  switch ((int32_t) ptr->tag) {
    case 3: {
      break;
    }
  }
}

void hermes_cardano_api_sync_slot_free(hermes_cardano_api_sync_slot_t *ptr) {
  switch ((int32_t) ptr->tag) {
    case 1: {
      break;
    }
  }
}

__attribute__((__import_module__("hermes:cardano/api"), __import_name__("[resource-drop]network")))
extern void __wasm_import_hermes_cardano_api_network_drop(int32_t handle);

void hermes_cardano_api_network_drop_own(hermes_cardano_api_own_network_t handle) {
  __wasm_import_hermes_cardano_api_network_drop(handle.__handle);
}

hermes_cardano_api_borrow_network_t hermes_cardano_api_borrow_network(hermes_cardano_api_own_network_t arg) {
  return (hermes_cardano_api_borrow_network_t) { arg.__handle };
}

__attribute__((__import_module__("hermes:cardano/api"), __import_name__("[resource-drop]block")))
extern void __wasm_import_hermes_cardano_api_block_drop(int32_t handle);

void hermes_cardano_api_block_drop_own(hermes_cardano_api_own_block_t handle) {
  __wasm_import_hermes_cardano_api_block_drop(handle.__handle);
}

hermes_cardano_api_borrow_block_t hermes_cardano_api_borrow_block(hermes_cardano_api_own_block_t arg) {
  return (hermes_cardano_api_borrow_block_t) { arg.__handle };
}

__attribute__((__import_module__("hermes:cardano/api"), __import_name__("[resource-drop]transaction")))
extern void __wasm_import_hermes_cardano_api_transaction_drop(int32_t handle);

void hermes_cardano_api_transaction_drop_own(hermes_cardano_api_own_transaction_t handle) {
  __wasm_import_hermes_cardano_api_transaction_drop(handle.__handle);
}

hermes_cardano_api_borrow_transaction_t hermes_cardano_api_borrow_transaction(hermes_cardano_api_own_transaction_t arg) {
  return (hermes_cardano_api_borrow_transaction_t) { arg.__handle };
}

__attribute__((__import_module__("hermes:cardano/api"), __import_name__("[resource-drop]subscription-id")))
extern void __wasm_import_hermes_cardano_api_subscription_id_drop(int32_t handle);

void hermes_cardano_api_subscription_id_drop_own(hermes_cardano_api_own_subscription_id_t handle) {
  __wasm_import_hermes_cardano_api_subscription_id_drop(handle.__handle);
}

hermes_cardano_api_borrow_subscription_id_t hermes_cardano_api_borrow_subscription_id(hermes_cardano_api_own_subscription_id_t arg) {
  return (hermes_cardano_api_borrow_subscription_id_t) { arg.__handle };
}

void hermes_cardano_api_result_own_network_create_network_error_free(hermes_cardano_api_result_own_network_create_network_error_t *ptr) {
  if (!ptr->is_err) {
  } else {
  }
}

void hermes_cardano_api_result_u32_subscribe_error_free(hermes_cardano_api_result_u32_subscribe_error_t *ptr) {
  if (!ptr->is_err) {
  } else {
  }
}

void stub_option_slot_free(stub_option_slot_t *ptr) {
  if (ptr->is_some) {
  }
}

void hermes_cardano_api_option_own_block_free(hermes_cardano_api_option_own_block_t *ptr) {
  if (ptr->is_some) {
  }
}

void stub_option_tuple2_slot_slot_free(stub_option_tuple2_slot_slot_t *ptr) {
  if (ptr->is_some) {
  }
}

void hermes_cardano_api_result_bool_block_error_free(hermes_cardano_api_result_bool_block_error_t *ptr) {
  if (!ptr->is_err) {
  } else {
  }
}

void hermes_cardano_api_result_own_transaction_transaction_error_free(hermes_cardano_api_result_own_transaction_transaction_error_t *ptr) {
  if (!ptr->is_err) {
  } else {
  }
}

void stub_option_cbor_free(stub_option_cbor_t *ptr) {
  if (ptr->is_some) {
    hermes_cardano_api_cbor_free(&ptr->val);
  }
}

void stub_option_txn_hash_free(stub_option_txn_hash_t *ptr) {
  if (ptr->is_some) {
  }
}

void hermes_cardano_event_on_block_cbor_free(hermes_cardano_event_on_block_cbor_t *ptr) {
  hermes_cbor_api_cbor_free(ptr);
}

void event_cbor_free(event_cbor_t *ptr) {
  hermes_cbor_api_cbor_free(ptr);
}

// Component Adapters

bool hermes_init_event_init(void) {
  int32_t ret = __wasm_import_hermes_init_event_init();
  return ret;
}

bool hermes_hash_api_blake2s(hermes_hash_api_bstr_t *buf, uint8_t *maybe_outlen, hermes_hash_api_bstr_t *ret, hermes_hash_api_errno_t *err) {
  __attribute__((__aligned__(sizeof(void*))))
  uint8_t ret_area[(3*sizeof(void*))];
  stub_option_u8_t outlen;
  outlen.is_some = maybe_outlen != NULL;if (maybe_outlen) {
    outlen.val = *maybe_outlen;
  }
  int32_t option;
  int32_t option1;
  if ((outlen).is_some) {
    const uint8_t *payload0 = &(outlen).val;
    option = 1;
    option1 = (int32_t) (*payload0);
  } else {
    option = 0;
    option1 = 0;
  }
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_hermes_hash_api_blake2s((uint8_t *) (*buf).ptr, (*buf).len, option, option1, ptr);
  hermes_hash_api_result_bstr_errno_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (hermes_binary_api_bstr_t) { (uint8_t*)(*((uint8_t **) (ptr + sizeof(void*)))), (*((size_t*) (ptr + (2*sizeof(void*))))) };
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (int32_t) *((uint8_t*) (ptr + sizeof(void*)));
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

bool hermes_hash_api_blake2smac(hermes_hash_api_bstr_t *buf, uint8_t *maybe_outlen, hermes_hash_api_bstr_t *key, hermes_hash_api_bstr_t *maybe_salt, hermes_hash_api_bstr_t *maybe_personal, hermes_hash_api_bstr_t *ret, hermes_hash_api_errno_t *err) {
  __attribute__((__aligned__(sizeof(void*))))
  uint8_t ret_area[(3*sizeof(void*))];
  stub_option_u8_t outlen;
  outlen.is_some = maybe_outlen != NULL;if (maybe_outlen) {
    outlen.val = *maybe_outlen;
  }
  stub_option_bstr_t salt;
  salt.is_some = maybe_salt != NULL;if (maybe_salt) {
    salt.val = *maybe_salt;
  }
  stub_option_bstr_t personal;
  personal.is_some = maybe_personal != NULL;if (maybe_personal) {
    personal.val = *maybe_personal;
  }
  int32_t option;
  int32_t option1;
  if ((outlen).is_some) {
    const uint8_t *payload0 = &(outlen).val;
    option = 1;
    option1 = (int32_t) (*payload0);
  } else {
    option = 0;
    option1 = 0;
  }
  int32_t option4;
  uint8_t * option5;
  size_t option6;
  if ((salt).is_some) {
    const hermes_hash_api_bstr_t *payload3 = &(salt).val;
    option4 = 1;
    option5 = (uint8_t *) (*payload3).ptr;
    option6 = (*payload3).len;
  } else {
    option4 = 0;
    option5 = 0;
    option6 = 0;
  }
  int32_t option9;
  uint8_t * option10;
  size_t option11;
  if ((personal).is_some) {
    const hermes_hash_api_bstr_t *payload8 = &(personal).val;
    option9 = 1;
    option10 = (uint8_t *) (*payload8).ptr;
    option11 = (*payload8).len;
  } else {
    option9 = 0;
    option10 = 0;
    option11 = 0;
  }
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_hermes_hash_api_blake2smac((uint8_t *) (*buf).ptr, (*buf).len, option, option1, (uint8_t *) (*key).ptr, (*key).len, option4, option5, option6, option9, option10, option11, ptr);
  hermes_hash_api_result_bstr_errno_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (hermes_binary_api_bstr_t) { (uint8_t*)(*((uint8_t **) (ptr + sizeof(void*)))), (*((size_t*) (ptr + (2*sizeof(void*))))) };
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (int32_t) *((uint8_t*) (ptr + sizeof(void*)));
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

bool hermes_hash_api_blake2b(hermes_hash_api_bstr_t *buf, uint8_t *maybe_outlen, hermes_hash_api_bstr_t *ret, hermes_hash_api_errno_t *err) {
  __attribute__((__aligned__(sizeof(void*))))
  uint8_t ret_area[(3*sizeof(void*))];
  stub_option_u8_t outlen;
  outlen.is_some = maybe_outlen != NULL;if (maybe_outlen) {
    outlen.val = *maybe_outlen;
  }
  int32_t option;
  int32_t option1;
  if ((outlen).is_some) {
    const uint8_t *payload0 = &(outlen).val;
    option = 1;
    option1 = (int32_t) (*payload0);
  } else {
    option = 0;
    option1 = 0;
  }
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_hermes_hash_api_blake2b((uint8_t *) (*buf).ptr, (*buf).len, option, option1, ptr);
  hermes_hash_api_result_bstr_errno_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (hermes_binary_api_bstr_t) { (uint8_t*)(*((uint8_t **) (ptr + sizeof(void*)))), (*((size_t*) (ptr + (2*sizeof(void*))))) };
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (int32_t) *((uint8_t*) (ptr + sizeof(void*)));
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

bool hermes_hash_api_blake2bmac(hermes_hash_api_bstr_t *buf, uint8_t *maybe_outlen, hermes_hash_api_bstr_t *key, hermes_hash_api_bstr_t *maybe_salt, hermes_hash_api_bstr_t *maybe_personal, hermes_hash_api_bstr_t *ret, hermes_hash_api_errno_t *err) {
  __attribute__((__aligned__(sizeof(void*))))
  uint8_t ret_area[(3*sizeof(void*))];
  stub_option_u8_t outlen;
  outlen.is_some = maybe_outlen != NULL;if (maybe_outlen) {
    outlen.val = *maybe_outlen;
  }
  stub_option_bstr_t salt;
  salt.is_some = maybe_salt != NULL;if (maybe_salt) {
    salt.val = *maybe_salt;
  }
  stub_option_bstr_t personal;
  personal.is_some = maybe_personal != NULL;if (maybe_personal) {
    personal.val = *maybe_personal;
  }
  int32_t option;
  int32_t option1;
  if ((outlen).is_some) {
    const uint8_t *payload0 = &(outlen).val;
    option = 1;
    option1 = (int32_t) (*payload0);
  } else {
    option = 0;
    option1 = 0;
  }
  int32_t option4;
  uint8_t * option5;
  size_t option6;
  if ((salt).is_some) {
    const hermes_hash_api_bstr_t *payload3 = &(salt).val;
    option4 = 1;
    option5 = (uint8_t *) (*payload3).ptr;
    option6 = (*payload3).len;
  } else {
    option4 = 0;
    option5 = 0;
    option6 = 0;
  }
  int32_t option9;
  uint8_t * option10;
  size_t option11;
  if ((personal).is_some) {
    const hermes_hash_api_bstr_t *payload8 = &(personal).val;
    option9 = 1;
    option10 = (uint8_t *) (*payload8).ptr;
    option11 = (*payload8).len;
  } else {
    option9 = 0;
    option10 = 0;
    option11 = 0;
  }
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_hermes_hash_api_blake2bmac((uint8_t *) (*buf).ptr, (*buf).len, option, option1, (uint8_t *) (*key).ptr, (*key).len, option4, option5, option6, option9, option10, option11, ptr);
  hermes_hash_api_result_bstr_errno_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (hermes_binary_api_bstr_t) { (uint8_t*)(*((uint8_t **) (ptr + sizeof(void*)))), (*((size_t*) (ptr + (2*sizeof(void*))))) };
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (int32_t) *((uint8_t*) (ptr + sizeof(void*)));
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

bool hermes_hash_api_blake3(hermes_hash_api_bstr_t *buf, uint8_t *maybe_outlen, hermes_hash_api_bstr_t *maybe_key, hermes_hash_api_bstr_t *ret, hermes_hash_api_errno_t *err) {
  __attribute__((__aligned__(sizeof(void*))))
  uint8_t ret_area[(3*sizeof(void*))];
  stub_option_u8_t outlen;
  outlen.is_some = maybe_outlen != NULL;if (maybe_outlen) {
    outlen.val = *maybe_outlen;
  }
  stub_option_bstr_t key;
  key.is_some = maybe_key != NULL;if (maybe_key) {
    key.val = *maybe_key;
  }
  int32_t option;
  int32_t option1;
  if ((outlen).is_some) {
    const uint8_t *payload0 = &(outlen).val;
    option = 1;
    option1 = (int32_t) (*payload0);
  } else {
    option = 0;
    option1 = 0;
  }
  int32_t option4;
  uint8_t * option5;
  size_t option6;
  if ((key).is_some) {
    const hermes_hash_api_bstr_t *payload3 = &(key).val;
    option4 = 1;
    option5 = (uint8_t *) (*payload3).ptr;
    option6 = (*payload3).len;
  } else {
    option4 = 0;
    option5 = 0;
    option6 = 0;
  }
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_hermes_hash_api_blake3((uint8_t *) (*buf).ptr, (*buf).len, option, option1, option4, option5, option6, ptr);
  hermes_hash_api_result_bstr_errno_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (hermes_binary_api_bstr_t) { (uint8_t*)(*((uint8_t **) (ptr + sizeof(void*)))), (*((size_t*) (ptr + (2*sizeof(void*))))) };
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (int32_t) *((uint8_t*) (ptr + sizeof(void*)));
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

bool hermes_cardano_api_static_network_new(hermes_cardano_api_cardano_network_t *network, hermes_cardano_api_own_network_t *ret, hermes_cardano_api_create_network_error_t *err) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  int32_t variant;
  int32_t variant3;
  switch ((int32_t) (*network).tag) {
    case 0: {
      variant = 0;
      variant3 = 0;
      break;
    }
    case 1: {
      variant = 1;
      variant3 = 0;
      break;
    }
    case 2: {
      variant = 2;
      variant3 = 0;
      break;
    }
    case 3: {
      const uint32_t *payload2 = &(*network).val.testnet_magic;
      variant = 3;
      variant3 = (int32_t) (*payload2);
      break;
    }
  }
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_hermes_cardano_api_static_network_new(variant, variant3, ptr);
  hermes_cardano_api_result_own_network_create_network_error_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (hermes_cardano_api_own_network_t) { *((int32_t*) (ptr + 4)) };
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (int32_t) *((uint8_t*) (ptr + 4));
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

bool hermes_cardano_api_method_network_subscribe_block(hermes_cardano_api_borrow_network_t self, hermes_cardano_api_sync_slot_t *start, uint32_t *ret, hermes_cardano_api_subscribe_error_t *err) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  int32_t variant;
  int64_t variant3;
  switch ((int32_t) (*start).tag) {
    case 0: {
      variant = 0;
      variant3 = 0;
      break;
    }
    case 1: {
      const hermes_cardano_api_slot_t *payload0 = &(*start).val.specific;
      variant = 1;
      variant3 = (int64_t) (*payload0);
      break;
    }
    case 2: {
      variant = 2;
      variant3 = 0;
      break;
    }
    case 3: {
      variant = 3;
      variant3 = 0;
      break;
    }
  }
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_hermes_cardano_api_method_network_subscribe_block((self).__handle, variant, variant3, ptr);
  hermes_cardano_api_result_u32_subscribe_error_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (uint32_t) (*((int32_t*) (ptr + 4)));
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (int32_t) *((uint8_t*) (ptr + 4));
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

bool hermes_cardano_api_method_network_subscribe_immutable_roll_forward(hermes_cardano_api_borrow_network_t self, hermes_cardano_api_sync_slot_t *start, uint32_t *ret, hermes_cardano_api_subscribe_error_t *err) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  int32_t variant;
  int64_t variant3;
  switch ((int32_t) (*start).tag) {
    case 0: {
      variant = 0;
      variant3 = 0;
      break;
    }
    case 1: {
      const hermes_cardano_api_slot_t *payload0 = &(*start).val.specific;
      variant = 1;
      variant3 = (int64_t) (*payload0);
      break;
    }
    case 2: {
      variant = 2;
      variant3 = 0;
      break;
    }
    case 3: {
      variant = 3;
      variant3 = 0;
      break;
    }
  }
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_hermes_cardano_api_method_network_subscribe_immutable_roll_forward((self).__handle, variant, variant3, ptr);
  hermes_cardano_api_result_u32_subscribe_error_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (uint32_t) (*((int32_t*) (ptr + 4)));
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (int32_t) *((uint8_t*) (ptr + 4));
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

bool hermes_cardano_api_method_network_get_block(hermes_cardano_api_borrow_network_t self, hermes_cardano_api_slot_t *maybe_start, int64_t step, hermes_cardano_api_own_block_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  stub_option_slot_t start;
  start.is_some = maybe_start != NULL;if (maybe_start) {
    start.val = *maybe_start;
  }
  int32_t option;
  int64_t option1;
  if ((start).is_some) {
    const hermes_cardano_api_slot_t *payload0 = &(start).val;
    option = 1;
    option1 = (int64_t) (*payload0);
  } else {
    option = 0;
    option1 = 0;
  }
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_hermes_cardano_api_method_network_get_block((self).__handle, option, option1, step, ptr);
  hermes_cardano_api_option_own_block_t option2;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      option2.is_some = false;
      break;
    }
    case 1: {
      option2.is_some = true;
      option2.val = (hermes_cardano_api_own_block_t) { *((int32_t*) (ptr + 4)) };
      break;
    }
  }
  *ret = option2.val;
  return option2.is_some;
}

bool hermes_cardano_api_method_network_get_tips(hermes_cardano_api_borrow_network_t self, stub_tuple2_slot_slot_t *ret) {
  __attribute__((__aligned__(8)))
  uint8_t ret_area[24];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_hermes_cardano_api_method_network_get_tips((self).__handle, ptr);
  stub_option_tuple2_slot_slot_t option;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      option.is_some = false;
      break;
    }
    case 1: {
      option.is_some = true;
      option.val = (stub_tuple2_slot_slot_t) {
        (hermes_cardano_api_slot_t) (uint64_t) (*((int64_t*) (ptr + 8))),
        (hermes_cardano_api_slot_t) (uint64_t) (*((int64_t*) (ptr + 16))),
      };
      break;
    }
  }
  *ret = option.val;
  return option.is_some;
}

bool hermes_cardano_api_method_block_is_immutable(hermes_cardano_api_borrow_block_t self) {
  int32_t ret = __wasm_import_hermes_cardano_api_method_block_is_immutable((self).__handle);
  return ret;
}

bool hermes_cardano_api_method_block_is_rollback(hermes_cardano_api_borrow_block_t self, bool *ret, hermes_cardano_api_block_error_t *err) {
  __attribute__((__aligned__(1)))
  uint8_t ret_area[2];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_hermes_cardano_api_method_block_is_rollback((self).__handle, ptr);
  hermes_cardano_api_result_bool_block_error_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (int32_t) *((uint8_t*) (ptr + 1));
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (int32_t) *((uint8_t*) (ptr + 1));
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

bool hermes_cardano_api_method_block_get_txn(hermes_cardano_api_borrow_block_t self, hermes_cardano_api_txn_idx_t index, hermes_cardano_api_own_transaction_t *ret, hermes_cardano_api_transaction_error_t *err) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_hermes_cardano_api_method_block_get_txn((self).__handle, (int32_t) (index), ptr);
  hermes_cardano_api_result_own_transaction_transaction_error_t result;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (hermes_cardano_api_own_transaction_t) { *((int32_t*) (ptr + 4)) };
      break;
    }
    case 1: {
      result.is_err = true;
      result.val.err = (int32_t) *((uint8_t*) (ptr + 4));
      break;
    }
  }
  if (!result.is_err) {
    *ret = result.val.ok;
    return 1;
  } else {
    *err = result.val.err;
    return 0;
  }
}

hermes_cardano_api_slot_t hermes_cardano_api_method_block_get_slot(hermes_cardano_api_borrow_block_t self) {
  int64_t ret = __wasm_import_hermes_cardano_api_method_block_get_slot((self).__handle);
  return (uint64_t) (ret);
}

void hermes_cardano_api_method_block_raw(hermes_cardano_api_borrow_block_t self, hermes_cardano_api_cbor_t *ret) {
  __attribute__((__aligned__(sizeof(void*))))
  uint8_t ret_area[(2*sizeof(void*))];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_hermes_cardano_api_method_block_raw((self).__handle, ptr);
  *ret = (hermes_binary_api_bstr_t) { (uint8_t*)(*((uint8_t **) (ptr + 0))), (*((size_t*) (ptr + sizeof(void*)))) };
}

bool hermes_cardano_api_method_transaction_get_metadata(hermes_cardano_api_borrow_transaction_t self, uint64_t label, hermes_cardano_api_cbor_t *ret) {
  __attribute__((__aligned__(sizeof(void*))))
  uint8_t ret_area[(3*sizeof(void*))];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_hermes_cardano_api_method_transaction_get_metadata((self).__handle, (int64_t) (label), ptr);
  stub_option_cbor_t option;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      option.is_some = false;
      break;
    }
    case 1: {
      option.is_some = true;
      option.val = (hermes_binary_api_bstr_t) { (uint8_t*)(*((uint8_t **) (ptr + sizeof(void*)))), (*((size_t*) (ptr + (2*sizeof(void*))))) };
      break;
    }
  }
  *ret = option.val;
  return option.is_some;
}

bool hermes_cardano_api_method_transaction_get_txn_hash(hermes_cardano_api_borrow_transaction_t self, hermes_cardano_api_txn_hash_t *ret) {
  __attribute__((__aligned__(8)))
  uint8_t ret_area[40];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_hermes_cardano_api_method_transaction_get_txn_hash((self).__handle, ptr);
  stub_option_txn_hash_t option;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      option.is_some = false;
      break;
    }
    case 1: {
      option.is_some = true;
      option.val = (hermes_binary_api_b256_t) {
        (uint64_t) (uint64_t) (*((int64_t*) (ptr + 8))),
        (uint64_t) (uint64_t) (*((int64_t*) (ptr + 16))),
        (uint64_t) (uint64_t) (*((int64_t*) (ptr + 24))),
        (uint64_t) (uint64_t) (*((int64_t*) (ptr + 32))),
      };
      break;
    }
  }
  *ret = option.val;
  return option.is_some;
}

bool hermes_cardano_api_method_transaction_raw(hermes_cardano_api_borrow_transaction_t self, hermes_cardano_api_cbor_t *ret) {
  __attribute__((__aligned__(sizeof(void*))))
  uint8_t ret_area[(3*sizeof(void*))];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_hermes_cardano_api_method_transaction_raw((self).__handle, ptr);
  stub_option_cbor_t option;
  switch ((int32_t) *((uint8_t*) (ptr + 0))) {
    case 0: {
      option.is_some = false;
      break;
    }
    case 1: {
      option.is_some = true;
      option.val = (hermes_binary_api_bstr_t) { (uint8_t*)(*((uint8_t **) (ptr + sizeof(void*)))), (*((size_t*) (ptr + (2*sizeof(void*))))) };
      break;
    }
  }
  *ret = option.val;
  return option.is_some;
}

void hermes_cardano_api_method_subscription_id_get_network(hermes_cardano_api_borrow_subscription_id_t self, hermes_cardano_api_cardano_network_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_hermes_cardano_api_method_subscription_id_get_network((self).__handle, ptr);
  hermes_cardano_api_cardano_network_t variant;
  variant.tag = (int32_t) *((uint8_t*) (ptr + 0));
  switch ((int32_t) variant.tag) {
    case 0: {
      break;
    }
    case 1: {
      break;
    }
    case 2: {
      break;
    }
    case 3: {
      variant.val.testnet_magic = (uint32_t) (*((int32_t*) (ptr + 4)));
      break;
    }
  }
  *ret = variant;
}

void hermes_cardano_api_method_subscription_id_unsubscribe(hermes_cardano_api_borrow_subscription_id_t self) {
  __wasm_import_hermes_cardano_api_method_subscription_id_unsubscribe((self).__handle);
}

void hermes_cardano_event_on_block_on_cardano_block(hermes_cardano_event_on_block_borrow_subscription_id_t subscription_id, hermes_cardano_event_on_block_borrow_block_t block) {
  __wasm_import_hermes_cardano_event_on_block_on_cardano_block((subscription_id).__handle, (block).__handle);
}

void hermes_cardano_event_on_immutable_roll_forward_on_cardano_immutable_roll_forward(hermes_cardano_event_on_immutable_roll_forward_borrow_subscription_id_t subscription_id, hermes_cardano_event_on_immutable_roll_forward_borrow_block_t block) {
  __wasm_import_hermes_cardano_event_on_immutable_roll_forward_on_cardano_immutable_roll_forward((subscription_id).__handle, (block).__handle);
}

__attribute__((__export_name__("event#init")))
int32_t __wasm_export_event_init(void) {
  bool ret = event_init();
  return ret;
}

__attribute__((__export_name__("event#on-cardano-block")))
void __wasm_export_event_on_cardano_block(int32_t arg, int32_t arg0) {
  int32_t borrow = 0;
  int32_t borrow1 = 0;
  borrow = arg;
  borrow1 = arg0;
  event_on_cardano_block((event_borrow_subscription_id_t) { arg }, (event_borrow_block_t) { arg0 });
  if (borrow != 0) {
    __wasm_import_hermes_cardano_api_subscription_id_drop(borrow);
  }
  if (borrow1 != 0) {
    __wasm_import_hermes_cardano_api_block_drop(borrow1);
  }
}

__attribute__((__export_name__("event#on-cardano-immutable-roll-forward")))
void __wasm_export_event_on_cardano_immutable_roll_forward(int32_t arg, int32_t arg0) {
  int32_t borrow = 0;
  int32_t borrow1 = 0;
  borrow = arg;
  borrow1 = arg0;
  event_on_cardano_immutable_roll_forward((event_borrow_subscription_id_t) { arg }, (event_borrow_block_t) { arg0 });
  if (borrow != 0) {
    __wasm_import_hermes_cardano_api_subscription_id_drop(borrow);
  }
  if (borrow1 != 0) {
    __wasm_import_hermes_cardano_api_block_drop(borrow1);
  }
}

// Ensure that the *_component_type.o object is linked in

extern void __component_type_object_force_link_stub(void);
__attribute__((used))
void __component_type_object_force_link_stub_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_stub();
}
