VERSION 0.8

IMPORT github.com/input-output-hk/catalyst-ci/earthly/rust:v3.1.7 AS rust-ci
# Use when debugging cat-ci locally.
# IMPORT ../../catalyst-ci/earthly/rust AS rust-ci

IMPORT ../../wasi AS wasi
IMPORT ../../wasi-hermes-component-adapter AS wasi-hermes-component-adapter

# build : build the cardano integration test wasm component
build:
    DO rust-ci+SETUP

    COPY --dir src .
    COPY Cargo.toml .
    COPY wasi+build-rust-bindings/hermes.rs src/hermes.rs

    DO rust-ci+CARGO --args "build --target wasm32-unknown-unknown --release" \
        --output="wasm32-unknown-unknown/release/cardano_rte_test_component.wasm"

    # RUN cargo build --target wasm32-unknown-unknown --release

    COPY wasi-hermes-component-adapter+build/wasi-hermes-component-adapter.wasm .

    RUN wasm-tools component new -o cardano.wasm target/wasm32-unknown-unknown/release/cardano_rte_test_component.wasm --adapt wasi-hermes-component-adapter.wasm

    SAVE ARTIFACT cardano.wasm
