VERSION 0.8

IMPORT github.com/input-output-hk/catalyst-ci/earthly/rust:v3.2.03 AS rust-ci
# Use when debugging cat-ci locally.
# IMPORT ../../catalyst-ci/earthly/rust AS rust-ci

IMPORT ../../wasi AS wasi
IMPORT ../../wasi-hermes-component-adapter AS wasi-hermes-component-adapter

# build : build the cardano integration test wasm component
build:
    DO rust-ci+SETUP

    COPY --keep-ts --dir src .
    COPY Cargo.toml .
    COPY wasi+build-rust-bindings/hermes.rs src/hermes.rs

    DO rust-ci+CARGO --args "build --target wasm32-wasip1 --release" \
        --output="wasm32-wasip1/release/cardano_rte_test_component.wasm"

    COPY wasi-hermes-component-adapter+build/wasi-hermes-component-adapter.wasm wasi_snapshot_preview1.wasm

    RUN wasm-tools component new -o cardano.wasm target/wasm32-wasip1/release/cardano_rte_test_component.wasm --adapt wasi_snapshot_preview1.wasm

    SAVE ARTIFACT cardano.wasm

# local-bindings : saves the Hermes rust bindings locally. This is useful for local development.
local-bindings:
    FROM wasi+build-rust-bindings

    SAVE ARTIFACT hermes.rs AS LOCAL src/hermes.rs
