VERSION 0.8

IMPORT github.com/input-output-hk/catalyst-ci/earthly/docs:v3.4.8 AS docs-ci

IMPORT .. AS repo
IMPORT ../hermes AS hermes
IMPORT ../wasm/wasi AS wasi
IMPORT ../wasm AS wasm

# cspell: words mkdocs runable

# Copy all the source we need to build the docs
src:
    # Common src setup
    DO docs-ci+SRC

    # Now copy into that any artifacts we pull from the builds.
    COPY --dir repo+repo-docs/repo /docs/includes
    # copy Rust docs
    COPY hermes+build/doc /docs/src/api/rust-docs
    # Copy the WASM Component model API Docs
    COPY --dir wasi+build/wasi-hermes-docs /docs/src/api/wasi-hermes
    # Copy the Hermes JSON Schemas and Examples
    COPY --dir hermes+json-schemas/schemas /docs/includes/
    COPY --dir wasm+wasi-src/wasi /docs/includes/


# Build the docs here.
docs:
    FROM +src

    DO docs-ci+BUILD

# Make a locally runable container that can serve the docs.
local:
    # Build a self contained service to show built docs locally.
    DO docs-ci+PACKAGE

    # Copy the static pages into the container
    COPY +docs/ /usr/share/nginx/html

    # This is a local only image, we do not publish it.
    SAVE IMAGE hermes-docs:latest
