VERSION 0.7
FROM rust:1.69-alpine
WORKDIR /work

build:
    FROM ../../..+tools

    # Get the current modules world definition and WASM interface dependencies.
    COPY --dir ../+wit/wit ./

    # Generate C binding for it.
    RUN wit-bindgen c wit

    # TODO - Build a C example
    #SAVE ARTIFACT hermes.* AS LOCAL c/
