package hermes:wasi;

/// This import every single API and exports every single entrypoint for a module.
/// Modules ONLY need to import API's they actually use.
/// Modules only need to implement the exports they require.
/// Take note of any permissions attached to a particular API before using it.
world hermes {

  /// All possible WASI compatible Imports
  import wasi:cli/environment@0.2.6;
  import wasi:cli/stdin@0.2.6;
  import wasi:cli/stdout@0.2.6;
  import wasi:cli/stderr@0.2.6;
  import wasi:clocks/monotonic-clock@0.2.6;
  import wasi:clocks/wall-clock@0.2.6;
  import wasi:filesystem/types@0.2.6;
  import wasi:filesystem/preopens@0.2.6;
  import wasi:random/random@0.2.6;
  import wasi:random/insecure@0.2.6;
  import wasi:random/insecure-seed@0.2.6;
  import wasi:http/outgoing-handler@0.2.6;
  import wasi:http/incoming-handler@0.2.6;

  /// All possible WASI compatible Exports
  export wasi:http/incoming-handler@0.2.6;
  

  /// All possible Hermes Imports/Exports
  include hermes:binary/all;
  include hermes:cardano/all;
  include hermes:cbor/all;
  include hermes:cron/all;
  include hermes:crypto/all;
  include hermes:hash/all;
  include hermes:init/all;
  include hermes:ipfs/all;
  include hermes:json/all;
  include hermes:kv-store/all;
  include hermes:localtime/all;
  include hermes:logging/all;
  include hermes:sqlite/all;
  include hermes:integration-test/all;
  include hermes:http-gateway/all;
}
