[package]
name = "byte-array-literals"
version.workspace = true
authors.workspace = true
edition.workspace = true
# inherited license from https://github.com/bytecodealliance/wasmtime
license = "Apache-2.0 WITH LLVM-exception"
publish = false

[lints]
workspace = true

[lib]
proc-macro = true
