VERSION 0.7

# build - generate a wasm component from a C stub file
build:
    FROM github.com/input-output-hk/catalyst-ci/earthly/wasm/c:v2.9.0+wasm-c-base

    ARG c_files="smoke-test.c"

    COPY ./$c_files .
    COPY ../..+wasi-src/wasi .

    RUN /scripts/std_build.py --wit_path="wit" --c_files=$c_files --out="smoke-test.wasm"

    SAVE ARTIFACT smoke-test.wasm
